# arm64-apple-darwin20.0.0-dyld
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-dyld.1
complete -c 'arm64-apple-darwin20.0.0-dyld' -s L -d 'option to otool (1)'
complete -c 'arm64-apple-darwin20.0.0-dyld' -o Lv -d 'option to otool (1)'

