# arm64-apple-darwin20.0.0-libtool
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-libtool.1
complete -c 'arm64-apple-darwin20.0.0-libtool' -o static -d 'Produce a statically linked (archive) library from the input files'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o dynamic -d 'Produce a dynamically linked shared library from the input files'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o install_name -d 'For a dynamic shared library, this specifies the file  name the library will …'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o compatibility_version -d 'For a dynamic shared library, this specifies the compatibility version number…'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o current_version -d 'For dynamic shared library files this specifies the current version number of…'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o noall_load -d 'For dynamic shared library files this specifies the the default behavior of l…'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s v -d 'Verbose mode, which prints the R ld (1) commands and R lipo (1) commands exec…'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s V -d 'Print the version of libtool'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o filelist -d 'The  listfile contains a list of file names and is an alternative way of spec…'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o arch_only -d 'This option causes libtool to build a library only for the specified  arch_ty…'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s s -d 'Produce the preferred type of table of contents, which results in faster link…'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s a -d 'Produce the original type of table of contents, whose order is based on the o…'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s c -d 'Include common symbols as definitions with respect to the table of contents'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s L -d 'Use the 4'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s T -d 'Truncate archive member names to 16 characters and don\'t use the 4'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s f -d 'Warns when the output archive is universal and R ar (1) will no longer be abl…'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s q -d 'Do nothing if a universal file would be created'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s D -d 'When building a static library, set archive contents\' user ids, group ids, da…'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s t -d 'This option used to request that  ranlib only ``touch\'\' the archives instead …'
complete -c 'arm64-apple-darwin20.0.0-libtool' -s o -d 'flag)'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o dylib -d 'once for each architecture present in the input objects and then lipo (1) to …'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o dynamiclib -d option
complete -c 'arm64-apple-darwin20.0.0-libtool' -s l
complete -c 'arm64-apple-darwin20.0.0-libtool' -o weak-l
complete -c 'arm64-apple-darwin20.0.0-libtool' -o search_paths_first
complete -c 'arm64-apple-darwin20.0.0-libtool' -o weak_library
complete -c 'arm64-apple-darwin20.0.0-libtool' -s y
complete -c 'arm64-apple-darwin20.0.0-libtool' -s u
complete -c 'arm64-apple-darwin20.0.0-libtool' -o init
complete -c 'arm64-apple-darwin20.0.0-libtool' -s i
complete -c 'arm64-apple-darwin20.0.0-libtool' -o seg1addr
complete -c 'arm64-apple-darwin20.0.0-libtool' -o segs_read_only_addr
complete -c 'arm64-apple-darwin20.0.0-libtool' -o segs_read_write_addr
complete -c 'arm64-apple-darwin20.0.0-libtool' -o seg_addr_table
complete -c 'arm64-apple-darwin20.0.0-libtool' -o seg_addr_table_filename
complete -c 'arm64-apple-darwin20.0.0-libtool' -o segprot
complete -c 'arm64-apple-darwin20.0.0-libtool' -o segalign
complete -c 'arm64-apple-darwin20.0.0-libtool' -o sectcreate
complete -c 'arm64-apple-darwin20.0.0-libtool' -o sectorder
complete -c 'arm64-apple-darwin20.0.0-libtool' -o sectorder_detail
complete -c 'arm64-apple-darwin20.0.0-libtool' -o sectalign
complete -c 'arm64-apple-darwin20.0.0-libtool' -o undefined
complete -c 'arm64-apple-darwin20.0.0-libtool' -o read_only_relocs
complete -c 'arm64-apple-darwin20.0.0-libtool' -o prebind
complete -c 'arm64-apple-darwin20.0.0-libtool' -o prebind_all_twolevel_modules
complete -c 'arm64-apple-darwin20.0.0-libtool' -o prebind_allow_overlap
complete -c 'arm64-apple-darwin20.0.0-libtool' -o noprebind
complete -c 'arm64-apple-darwin20.0.0-libtool' -o framework
complete -c 'arm64-apple-darwin20.0.0-libtool' -o weak_framework
complete -c 'arm64-apple-darwin20.0.0-libtool' -o umbrella
complete -c 'arm64-apple-darwin20.0.0-libtool' -o allowable_client
complete -c 'arm64-apple-darwin20.0.0-libtool' -o sub_umbrella
complete -c 'arm64-apple-darwin20.0.0-libtool' -o sub_library
complete -c 'arm64-apple-darwin20.0.0-libtool' -s F
complete -c 'arm64-apple-darwin20.0.0-libtool' -s U
complete -c 'arm64-apple-darwin20.0.0-libtool' -s Y
complete -c 'arm64-apple-darwin20.0.0-libtool' -o Sn
complete -c 'arm64-apple-darwin20.0.0-libtool' -o Si
complete -c 'arm64-apple-darwin20.0.0-libtool' -o Sp
complete -c 'arm64-apple-darwin20.0.0-libtool' -s S
complete -c 'arm64-apple-darwin20.0.0-libtool' -s X
complete -c 'arm64-apple-darwin20.0.0-libtool' -s x
complete -c 'arm64-apple-darwin20.0.0-libtool' -o whyload
complete -c 'arm64-apple-darwin20.0.0-libtool' -o all_load
complete -c 'arm64-apple-darwin20.0.0-libtool' -o arch_errors_fatal
complete -c 'arm64-apple-darwin20.0.0-libtool' -o dylib_file
complete -c 'arm64-apple-darwin20.0.0-libtool' -o run_init_lazily
complete -c 'arm64-apple-darwin20.0.0-libtool' -o final_output
complete -c 'arm64-apple-darwin20.0.0-libtool' -o macosx_version_min
complete -c 'arm64-apple-darwin20.0.0-libtool' -o multiply_defined
complete -c 'arm64-apple-darwin20.0.0-libtool' -o multiply_defined_unused
complete -c 'arm64-apple-darwin20.0.0-libtool' -o twolevel_namespace
complete -c 'arm64-apple-darwin20.0.0-libtool' -o twolevel_namespace_hints
complete -c 'arm64-apple-darwin20.0.0-libtool' -o flat_namespace
complete -c 'arm64-apple-darwin20.0.0-libtool' -o nomultidefs
complete -c 'arm64-apple-darwin20.0.0-libtool' -o headerpad
complete -c 'arm64-apple-darwin20.0.0-libtool' -o headerpad_max_install_names
complete -c 'arm64-apple-darwin20.0.0-libtool' -o weak_reference_mismatches
complete -c 'arm64-apple-darwin20.0.0-libtool' -s M
complete -c 'arm64-apple-darwin20.0.0-libtool' -o no_arch_warnings
complete -c 'arm64-apple-darwin20.0.0-libtool' -o single_module
complete -c 'arm64-apple-darwin20.0.0-libtool' -o multi_module
complete -c 'arm64-apple-darwin20.0.0-libtool' -o exported_symbols_list
complete -c 'arm64-apple-darwin20.0.0-libtool' -o unexported_symbols_list
complete -c 'arm64-apple-darwin20.0.0-libtool' -s m
complete -c 'arm64-apple-darwin20.0.0-libtool' -o dead_strip
complete -c 'arm64-apple-darwin20.0.0-libtool' -o no_dead_strip_inits_and_terms
complete -c 'arm64-apple-darwin20.0.0-libtool' -o executable_path
complete -c 'arm64-apple-darwin20.0.0-libtool' -o syslibroot
complete -c 'arm64-apple-darwin20.0.0-libtool' -o no_uuid -d 'See the ld (1) man page for details on these flags.  The flag'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o image_base -d 'is a synonym for'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o force_cpusubtype_ALL -d 'flag and passes the'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o arch -d 'flag so that the output is tagged with that cpusubtype'
complete -c 'arm64-apple-darwin20.0.0-libtool' -o no_warning_for_no_symbols -d 'Don\'t warn about file that have no symbols'

