# arm64-apple-darwin20.0.0-mtoc
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-mtoc.1
complete -c 'arm64-apple-darwin20.0.0-mtoc' -o subsystem -d 'specifies the EFI subsystem  type which can be R application ,  boot or  runt…'
complete -c 'arm64-apple-darwin20.0.0-mtoc' -o section_alignment -d 'Specifies the PECOFF section alignment'
complete -c 'arm64-apple-darwin20.0.0-mtoc' -o align -d 'Specifies the PECOFF file and section alignment'
complete -c 'arm64-apple-darwin20.0.0-mtoc' -o version -d 'Specifies the PECOFF  major and  minor versions for the MajorImageVersion and…'
complete -c 'arm64-apple-darwin20.0.0-mtoc' -o segalign -d 'when linking the Mach-O file'
complete -c 'arm64-apple-darwin20.0.0-mtoc' -s d -d 'Specifies the filename to be used to create a debug directory entry with'

