# arm64-apple-darwin20.0.0-segedit
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-segedit.1
complete -c 'arm64-apple-darwin20.0.0-segedit' -o extract -d 'Extracts each section specified by the segment and section names and places t…'
complete -c 'arm64-apple-darwin20.0.0-segedit' -o replace -d 'Replaces each section specified by the segment and section names and takes th…'
complete -c 'arm64-apple-darwin20.0.0-segedit' -o sectcreate -d option
complete -c 'arm64-apple-darwin20.0.0-segedit' -s l -d 'option to otool (1)'
complete -c 'arm64-apple-darwin20.0.0-segedit' -o output -d 'option must also be specified'

