# arm64-apple-darwin20.0.0-size
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-size.1
complete -c 'arm64-apple-darwin20.0.0-size' -s m -d 'Print the sizes of the Mach-O segments and sections as well as the total size…'
complete -c 'arm64-apple-darwin20.0.0-size' -s l -d 'When used with the  -m option, also print the addresses and offsets of the se…'
complete -c 'arm64-apple-darwin20.0.0-size' -s x -d 'When used with the  -m option, print the values in hexadecimal (with leading …'
complete -c 'arm64-apple-darwin20.0.0-size' -o arch -d 'Specifies the architecture, arch_type, of the file for size (1) to operate on…'

