# arm64-apple-darwin20.0.0-codesign_allocate
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-codesign_allocate.1
complete -c 'arm64-apple-darwin20.0.0-codesign_allocate' -s i -d 'specifies the input file as  oldfile'
complete -c 'arm64-apple-darwin20.0.0-codesign_allocate' -s o -d 'specifies the output file as  newfile'
complete -c 'arm64-apple-darwin20.0.0-codesign_allocate' -s a -d 'specifies for the architecture  arch that the size of the code signing data i…'
complete -c 'arm64-apple-darwin20.0.0-codesign_allocate' -s A -d 'specifies for the architecture as a pair of decimal integers for the cputype …'
complete -c 'arm64-apple-darwin20.0.0-codesign_allocate' -s r -d 'remove the code signature data and the LC_CODE_SIGNATURE load command'
complete -c 'arm64-apple-darwin20.0.0-codesign_allocate' -s p -d 'page align the code signature data by padding string table and changing its s…'

