# bash
# Autogenerated from man page /opt/homebrew/share/man/man1/bash.1
complete -c bash -o 'd\'\'' -d 'null argument removal'
complete -c bash -s R -d 'True if the shell variable varname is set and is a name reference'
complete -c bash -s I -d 'option causes local variables to inherit the attributes (except the nameref a…'

