# bear-citnames
# Autogenerated from man page /opt/homebrew/share/man/man1/bear-citnames.1
complete -c bear-citnames -l version -d 'Print version number'
complete -c bear-citnames -l help -d 'Print help message'
complete -c bear-citnames -l verbose -d 'Enable verbose logging'
complete -c bear-citnames -l input -d 'Specify input file.  (Default file name provided'
complete -c bear-citnames -l output -d 'Specify output file.  (Default file name provided'
complete -c bear-citnames -l append -d 'Use previously generated output file and append the new entries to it'
complete -c bear-citnames -l run-checks -d 'Allow the program to verify file location checks on the current machine it ru…'
complete -c bear-citnames -l config -d 'Specify a configuration file'

