# bear
# Autogenerated from man page /opt/homebrew/share/man/man1/bear.1
complete -c bear -l version -d 'Print version number'
complete -c bear -l help -d 'Print help message'
complete -c bear -l verbose -d 'Enable verbose logging'
complete -c bear -l output -d 'Specify output file.  (Default file name provided'
complete -c bear -l append -d 'Use previously generated output file and append the new entries to it'
complete -c bear -l config -d 'Specify a configuration file'
complete -c bear -l force-preload -d 'Force to use the dynamic linker method of \\f[C]intercept\\f[R] command'
complete -c bear -l force-wrapper -d 'Force to use the compiler wrapper method of intercept command.  COMMANDS'

