# bear-intercept
# Autogenerated from man page /opt/homebrew/share/man/man1/bear-intercept.1
complete -c bear-intercept -l version -d 'Print version number'
complete -c bear-intercept -l help -d 'Print help message'
complete -c bear-intercept -l verbose -d 'Enable verbose logging'
complete -c bear-intercept -l output -d 'Specify output file.  (Default file name provided'
complete -c bear-intercept -l force-preload -d 'Force to use the preload method to intercept the children processes'
complete -c bear-intercept -l force-wrapper -d 'Force to use the wrapper method to intercept the children processes'

