# bootpd
# Autogenerated from man page /usr/share/man/man8/bootpd.8
complete -c bootpd -s m -d 'Enable NetBoot 1. 0 (BOOTP-based) service'
complete -c bootpd -s N -d 'Enable NetBoot 2. 0 (BSDP/DHCP-based) service'

