# bsdtar
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/bsdtar.1
complete -c bsdtar -l no-read-sparse -d '(c, r, u modes only) Do not read sparse file information from disk'
complete -c bsdtar -l read-sparse -d '(c, r, u modes only) Read sparse file information from disk'

