# cjpeg
# Autogenerated from man page /opt/homebrew/share/man/man1/cjpeg.1
complete -c cjpeg -o precision -d 'Create JPEG file with N-bit data precision.   N is 8, 12, or 16; default is 8'
complete -c cjpeg -o lossless -d 'Create a lossless JPEG file using the specified predictor selection value (1 …'
complete -c cjpeg -o icc -d 'Embed ICC color management profile contained in the specified file'
complete -c cjpeg -o memdst -d 'Compress to memory instead of a file'
complete -c cjpeg -o report -d 'Report compression progress'
complete -c cjpeg -o strict -d 'Treat all warnings as fatal'
complete -c cjpeg -o version -d 'Print version information and exit'

