# cryptexctl-install
# Autogenerated from man page /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/cryptexctl-install.1
complete -c cryptexctl-install -s V -d 'The name of the cryptex CRYPTEX-DIRECTORY The path to the cryptex bundle dire…'

