# dbsessmgr
# Autogenerated from man page /usr/local/share/man/man1/dbsessmgr.1
complete -c dbsessmgr -l clean -d 'Remove all expired sessions'
complete -c dbsessmgr -l remove -d 'Delete all sessions'
complete -c dbsessmgr -l show -d 'Display session data'

