# diff3
# Autogenerated from man page /usr/share/man/man1/diff3.1
complete -c diff3 -l ed -d 'Output unmerged changes from OLDFILE to YOURFILE into MYFILE'
complete -c diff3 -l show-overlap -d 'Output unmerged changes, bracketing conflicts'
complete -c diff3 -l show-all -d 'Output all changes, bracketing conflicts'
complete -c diff3 -l overlap-only -d 'Output overlapping changes'
complete -c diff3 -l easy-only -d 'Output unmerged nonoverlapping changes'
complete -c diff3 -l merge -d 'Output merged file instead of ed script (default -A)'
complete -c diff3 -l label -d 'Use LABEL instead of file name'
complete -c diff3 -l text -d 'Treat all files as text'
complete -c diff3 -l initial-tab -d 'Make tabs line up by prepending a tab'
complete -c diff3 -s v -d 'Output version info'

