# dotnet-nuget-enable-source
# Autogenerated from man page /opt/homebrew/share/man/man1/dotnet-nuget-enable-source.1
complete -c dotnet-nuget-enable-source -l configfile -d 'The NuGet configuration file (nuget. config) to use'

