# dotnet-workload-uninstall
# Autogenerated from man page /opt/homebrew/share/man/man1/dotnet-workload-uninstall.1
complete -c dotnet-workload-uninstall -s '?' -s h -l help -d 'Prints out a description of how to use the command'

