# dotnet-new-list
# Autogenerated from man page /opt/homebrew/share/man/man1/dotnet-new-list.1
complete -c dotnet-new-list -l author -d 'Filters templates based on template author.  Partial match is supported'
complete -c dotnet-new-list -l columns -d 'Comma-separated list of columns to display in the output'
complete -c dotnet-new-list -l columns-all -d 'Displays all columns in the output.  Available since . NET Core 5. 0. 300 SDK'
complete -c dotnet-new-list -o lang -l language -d 'Filters templates based on language supported by the template'
complete -c dotnet-new-list -l tag -d 'Filters templates based on template tags'
complete -c dotnet-new-list -l type -d 'Filters templates based on template type'

