# dotnet-tool-run
# Autogenerated from man page /opt/homebrew/share/man/man1/dotnet-tool-run.1
complete -c dotnet-tool-run -s '?' -s h -l help -d 'Prints out a description of how to use the command'

