# dotnet-remove-package
# Autogenerated from man page /opt/homebrew/share/man/man1/dotnet-remove-package.1
complete -c dotnet-remove-package -s '?' -s h -l help -d 'Prints out a description of how to use the command'

