# dotnet-new-install
# Autogenerated from man page /opt/homebrew/share/man/man1/dotnet-new-install.1
complete -c dotnet-new-install -l interactive -d 'Allows the command to stop and wait for user input or action'
complete -c dotnet-new-install -l nuget-source -d 'By default, dotnet new --install uses the hierarchy of NuGet configuration fi…'

