# dotnet-workload-list
# Autogenerated from man page /opt/homebrew/share/man/man1/dotnet-workload-list.1
complete -c dotnet-workload-list -s '?' -s h -l help -d 'Prints out a description of how to use the command'
complete -c dotnet-workload-list -s v -l verbosity -d 'Sets the verbosity level of the command'

