# fonttosfnt
# Autogenerated from man page /opt/X11/share/man/man1/fonttosfnt.1
complete -c fonttosfnt -s v -d 'Be verbose'
complete -c fonttosfnt -s c -d 'Do not crop glyphs'
complete -c fonttosfnt -s b -d 'Write byte-aligned glyph data'
complete -c fonttosfnt -s r -d 'Do not reencode fonts'
complete -c fonttosfnt -s g -d 'Set the type of scalable glyphs that we write'
complete -c fonttosfnt -s m -d 'Set the type of scalable metrics that we write'

