# FSTester
# Autogenerated from man page /usr/share/man/man1/FSTester.1
complete -c FSTester -s a -d 'Description of -a flag'
complete -c FSTester -s b -d 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

