# gfactor
# Autogenerated from man page /opt/homebrew/share/man/man1/gfactor.1
complete -c gfactor -s h -l exponents -d 'print repeated factors in form p^e unless e is 1'
complete -c gfactor -l help -d 'display this help and exit'
complete -c gfactor -l version -d 'output version information and exit AUTHOR Written by Paul Rubin, Torbjorn Gr…'

