# gh-cache-list
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-cache-list.1
complete -c gh-cache-list -s L -l limit -d 'Maximum number of caches to fetch'
complete -c gh-cache-list -s O -l order -d 'Order of caches returned: {asc|desc}'
complete -c gh-cache-list -s S -l sort -d 'Sort fetched caches: {created_at|last_accessed_at|size_in_bytes} OPTIONS INHE…'
complete -c gh-cache-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # List c…'

