# gh-project-field-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-field-delete.1
complete -c gh-project-field-delete -l format -d 'Output format: {json}'
complete -c gh-project-field-delete -l id -d 'ID of the field to delete SEE ALSO'

