# gh-project-mark-template
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-mark-template.1
complete -c gh-project-mark-template -l format -d 'Output format: {json}'
complete -c gh-project-mark-template -l owner -d 'Login of the org owner'
complete -c gh-project-mark-template -l undo -d 'Unmark the project as a template'

