# gh-repo-sync
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-sync.1
complete -c gh-repo-sync -l force -d 'by synced using a hard reset'
complete -c gh-repo-sync -s b -l branch -d 'Branch to sync (default: main branch)'
complete -c gh-repo-sync -s s -l source -d 'Source repository EXAMPLE # Sync local repository from remote parent $ gh rep…'

