# ghostid
# Autogenerated from man page /opt/homebrew/share/man/man1/ghostid.1
complete -c ghostid -l help -d 'display this help and exit'
complete -c ghostid -l version -d 'output version information and exit AUTHOR Written by Jim Meyering'

