# git-for-each-ref
# Autogenerated from man page /opt/homebrew/share/man/man1/git-for-each-ref.1
complete -c git-for-each-ref -l stdin -d 'If --stdin is supplied, then the list of patterns is read from standard input…'
complete -c git-for-each-ref -l omit-empty -d 'Do not print a newline after formatted refs where the format expands to the e…'
complete -c git-for-each-ref -l exclude -d 'If one or more patterns are given, only refs which do not match any excluded …'

