# git-lfs-uninstall
# Autogenerated from man page /opt/homebrew/share/man/man1/git-lfs-uninstall.1
complete -c git-lfs-uninstall -l local
complete -c git-lfs-uninstall -l worktree
complete -c git-lfs-uninstall -l system
complete -c git-lfs-uninstall -l skip-repo

