# git-rebase
# Autogenerated from man page /opt/homebrew/share/man/man1/git-rebase.1
complete -c git-rebase -l no-rebase-merges -d 'By default, a rebase will simply drop merge commits from the todo list, and p…'

