# git-lfs-clone
# Autogenerated from man page /opt/homebrew/share/man/man1/git-lfs-clone.1
complete -c git-lfs-clone -s I -l include
complete -c git-lfs-clone -s X -l exclude
complete -c git-lfs-clone -l skip-repo

