# git-lfs-unlock
# Autogenerated from man page /opt/homebrew/share/man/man1/git-lfs-unlock.1
complete -c git-lfs-unlock -l force -d OPTIONS
complete -c git-lfs-unlock -s r -l remote
complete -c git-lfs-unlock -s f
complete -c git-lfs-unlock -s i -l id
complete -c git-lfs-unlock -l json

