# git-send-email
# Autogenerated from man page /opt/homebrew/share/man/man1/git-send-email.1
complete -c git-send-email -l header-cmd -d 'Specify a command that is executed once per outgoing message and output RFC 2…'
complete -c git-send-email -l no-header-cmd -d 'Disable any header command in use'

