# git-lfs-checkout
# Autogenerated from man page /opt/homebrew/share/man/man1/git-lfs-checkout.1
complete -c git-lfs-checkout -l base
complete -c git-lfs-checkout -l ours
complete -c git-lfs-checkout -l theirs
complete -c git-lfs-checkout -l to

