# git-merge-tree
# Autogenerated from man page /opt/homebrew/share/man/man1/git-merge-tree.1
complete -c git-merge-tree -l merge-base -d 'Instead of finding the merge-bases for <branch1> and <branch2>, specify a mer…'
complete -c git-merge-tree -l stdin

