# git-lfs-ls-files
# Autogenerated from man page /opt/homebrew/share/man/man1/git-lfs-ls-files.1
complete -c git-lfs-ls-files -s l -l long
complete -c git-lfs-ls-files -s s -l size
complete -c git-lfs-ls-files -s d -l debug
complete -c git-lfs-ls-files -s a -l all
complete -c git-lfs-ls-files -l deleted
complete -c git-lfs-ls-files -s I -l include
complete -c git-lfs-ls-files -s X -l exclude
complete -c git-lfs-ls-files -s n -l name-only

