# git-pack-refs
# Autogenerated from man page /opt/homebrew/share/man/man1/git-pack-refs.1
complete -c git-pack-refs -l include -d 'Pack refs based on a glob(7) pattern'
complete -c git-pack-refs -l exclude -d 'Do not pack refs matching the given glob(7) pattern'
complete -c git-pack-refs -l no-include -d 'to clear and reset the list of patterns'
complete -c git-pack-refs -l no-exclude -d 'to clear and reset the list of patterns'

