# git-fetch
# Autogenerated from man page /opt/homebrew/share/man/man1/git-fetch.1
complete -c git-fetch -l porcelain -d 'Print the output to standard output in an easy-to-parse format for scripts'
complete -c git-fetch -l bundle-uri -d 'option behaves in git-clone(1).  git clone --bundle-uri will set the fetch'

