# git-cat-file
# Autogenerated from man page /opt/homebrew/share/man/man1/git-cat-file.1
complete -c git-cat-file -s Z -d 'Only meaningful with --batch, --batch-check, or --batch-command; input and ou…'

