# git-lfs-merge-driver
# Autogenerated from man page /opt/homebrew/share/man/man1/git-lfs-merge-driver.1
complete -c git-lfs-merge-driver -l ancestor
complete -c git-lfs-merge-driver -l current
complete -c git-lfs-merge-driver -l marker-size
complete -c git-lfs-merge-driver -l other
complete -c git-lfs-merge-driver -l program

