# git-notes
# Autogenerated from man page /opt/homebrew/share/man/man1/git-notes.1
complete -c git-notes -l separator -l separator -d 'Specify a string used as a custom inter-paragraph separator (a newline is add…'
complete -c git-notes -l stripspace -d 'Strip leading and trailing whitespace from the note message'
complete -c git-notes -l no-stripspace
complete -c git-notes -l no-separator

