# gsed
# Autogenerated from man page /opt/homebrew/share/man/man1/gsed.1
complete -c gsed -l help -d 'display this help and exit'
complete -c gsed -s n -l quiet -l silent -d 'suppress automatic printing of pattern space'
complete -c gsed -l debug -d 'annotate program execution'
complete -c gsed -s e -l expression -d 'add the script to the commands to be executed'
complete -c gsed -s f -l file -d 'add the contents of script-file to the commands to be executed'
complete -c gsed -l follow-symlinks -d 'follow symlinks when processing in place'
complete -c gsed -s i -l in-place -d 'edit files in place (makes backup if SUFFIX supplied)'
complete -c gsed -s l -l line-length -d 'specify the desired line-wrap length for the `l\' command'
complete -c gsed -l posix -d 'disable all GNU extensions'
complete -c gsed -s E -s r -l regexp-extended -d 'use extended regular expressions in the script (for portability use POSIX -E)'
complete -c gsed -s s -l separate -d 'consider files as separate rather than as a single, continuous long stream'
complete -c gsed -l sandbox -d 'operate in sandbox mode (disable e/r/w commands)'
complete -c gsed -s u -l unbuffered -d 'load minimal amounts of data from the input files and flush the output buffer…'
complete -c gsed -s z -l null-data -d 'separate lines by NUL characters'
complete -c gsed -l version -d 'output version information and exit'

