# gst-launch-1.0
# Autogenerated from man page /opt/homebrew/share/man/man1/gst-launch-1.0.1
complete -c 'gst-launch-1.0' -l no-position -d 'Do not print current position of pipeline'
complete -c 'gst-launch-1.0' -l force-position -d 'Allow printing current position of pipeline even if stdout is not a TTY'

