# gtk4-demo
# Autogenerated from man page /opt/homebrew/share/man/man1/gtk4-demo.1
complete -c gtk4-demo -s h -l help -d 'Show help options'
complete -c gtk4-demo -l version -d 'Show program version'
complete -c gtk4-demo -l list -d 'List available examples'
complete -c gtk4-demo -l run -d 'Run the named example.  Use --list to see the available examples'
complete -c gtk4-demo -l autoquit -d 'Quit after a short timeout.  This is intended for use with --run, e. g'

