# gtk4-widget-factory
# Autogenerated from man page /opt/homebrew/share/man/man1/gtk4-widget-factory.1
complete -c gtk4-widget-factory -s h -l help -d 'Show the application help'
complete -c gtk4-widget-factory -l version -d 'Show the application version'

