# gtsort
# Autogenerated from man page /opt/homebrew/share/man/man1/gtsort.1
complete -c gtsort -l help -d 'display this help and exit'
complete -c gtsort -l version -d 'output version information and exit AUTHOR Written by Mark Kettenis'

