# hstr
# Autogenerated from man page /opt/homebrew/share/man/man1/hstr.1
complete -c hstr -s h -l help -d 'Show help'
complete -c hstr -s n -l non-interactive -d 'Print filtered history on standard output and exit'
complete -c hstr -s k -l kill-last-command -d 'Delete the last command from history and exit'
complete -c hstr -s i -l insert-in-terminal -d 'Insert custom command to terminal prompt and exit'
complete -c hstr -s f -l favorites -d 'Show favorites view immediately'
complete -c hstr -s s -l show-configuration -d 'Show configuration to be added to the config file of the shell (~/'
complete -c hstr -s B -l show-bash-configuration -d 'Show Bash configuration to be added to ~/. bashrc'
complete -c hstr -s Z -l show-zsh-configuration -d 'Show Zsh configuration to be added to ~/. zshrc'
complete -c hstr -s b -l show-blacklist -d 'Show blacklist of commands to be filtered out before history processing'
complete -c hstr -s V -l version -d 'Show version information KEYS'

