# hwloc-patch
# Autogenerated from man page /opt/homebrew/share/man/man1/hwloc-patch.1
complete -c hwloc-patch -s R -l reverse -d 'Reverse the sense the difference file'
complete -c hwloc-patch -l version -d 'Report version and exit'
complete -c hwloc-patch -s h -l help -d 'Display help message and exit.  DESCRIPTION'

