# img2webp
# Autogenerated from man page /opt/homebrew/share/man/man1/img2webp.1
complete -c img2webp -o near_lossless -d 'Specify the level of near-lossless image preprocessing'
complete -c img2webp -o sharp_yuv -d 'Use more accurate and sharper RGB->YUV conversion if needed'

