# innochecksum
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/innochecksum.1
complete -c innochecksum -l help
complete -c innochecksum -s '?'
complete -c innochecksum -l info
complete -c innochecksum -s I
complete -c innochecksum -l version
complete -c innochecksum -s V
complete -c innochecksum -l verbose
complete -c innochecksum -s v
complete -c innochecksum -l log -d 'verbose mode, run: shell> innochecksum --verbose To turn off verbose mode, ru…'
complete -c innochecksum -l count
complete -c innochecksum -s c
complete -c innochecksum -l start-page
complete -c innochecksum -s s
complete -c innochecksum -l end-page
complete -c innochecksum -s e
complete -c innochecksum -l page
complete -c innochecksum -s p
complete -c innochecksum -l strict-check
complete -c innochecksum -s C
complete -c innochecksum -l no-check
complete -c innochecksum -s n
complete -c innochecksum -l write -d 'option.  If the'
complete -c innochecksum -l allow-mismatches
complete -c innochecksum -s a
complete -c innochecksum -s w
complete -c innochecksum -l page-type-summary
complete -c innochecksum -s S
complete -c innochecksum -l page-type-dump
complete -c innochecksum -s D
complete -c innochecksum -s l
complete -c innochecksum -l debug -d 'option, which was available in earlier releases'

