# ivstools
# Autogenerated from man page /opt/homebrew/share/man/man1/ivstools.1
complete -c ivstools -l convert
complete -c ivstools -l merge -d 'AUTHOR This manual page was written by Adam Cecile <gandalf@le-vert'

