# kinit
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/kinit.1
complete -c kinit -s V -d 'display verbose output'
complete -c kinit -s F -d 'requests non-forwardable tickets'
complete -c kinit -s P -d 'requests non-proxiable tickets'
complete -c kinit -s C -d 'requests canonicalization of the principal name, and allows the KDC to reply …'
complete -c kinit -s E -d 'treats the principal name as an enterprise name'
complete -c kinit -s i -d 'requests a ticket, obtained from a key in the local host\\(aqs keytab'
complete -c kinit -s n -d 'Requests anonymous processing'
complete -c kinit -s T -d 'Specifies the name of a credentials cache that already contains a ticket'
complete -c kinit -s X -d 'specify a pre-authentication attribute and value to be interpreted by pre-aut…'
complete -c kinit -l request-pac -l no-request-pac -d 'mutually exclusive'
complete -c kinit -s I -d 'Specifies the name of a credentials cache that already contains a ticket'

