# klist
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/klist.1
complete -c klist -s e -d 'Displays the encryption types of the session key and the ticket for each cred…'
complete -c klist -s A -d 'If a cache collection is available, displays the contents of all of the cache…'
complete -c klist -s a -d 'Display list of addresses in credentials'
complete -c klist -s n -d 'Show numeric addresses instead of reverse-resolving addresses'
complete -c klist -s C -d 'List configuration data that has been stored in the credentials cache when kl…'
complete -c klist -s k -d 'List keys held in a keytab file'
complete -c klist -s i -d 'In combination with -k, defaults to using the default client keytab instead o…'
complete -c klist -s t -d 'Display the time entry timestamps for each keytab entry in the keytab file'
complete -c klist -s K -d 'Display the value of the encryption key in each keytab entry in the keytab fi…'
complete -c klist -s d -d 'Display the authdata types (if any) for each entry'
complete -c klist -s V -d 'Display the Kerberos version number and exit'

