# knockd
# Autogenerated from man page /opt/homebrew/share/man/man1/knockd.1
complete -c knockd -s i -l interface -d 'Specify an interface to listen on.   The default is eth0'
complete -c knockd -s d -l daemon -d 'Become a daemon.   This is usually desired for normal server-like operation'
complete -c knockd -s c -l config -d 'Specify an alternate location for the config file.   Default is /etc/knockd'
complete -c knockd -s D -l debug -d 'Output debugging messages'
complete -c knockd -s l -l lookup -d 'Lookup DNS names for log entries'
complete -c knockd -s 4 -l only-ip-v4 -d 'Ignore packets from IPv6 and handle only IPv4'
complete -c knockd -s v -l verbose -d 'Output verbose status messages'
complete -c knockd -s V -l version -d 'Display the version'
complete -c knockd -s h -l help -d 'Syntax help'

