# knock
# Autogenerated from man page /opt/homebrew/share/man/man1/knock.1
complete -c knock -s u -l udp -d 'Make all port hits use UDP (default is TCP)'
complete -c knock -s d -l delay -d 'Wait <t> milliseconds between each port hit'
complete -c knock -s 4 -l ipv4 -d 'Force usage of IPv4'
complete -c knock -s 6 -l ipv6 -d 'Force usage of IPv6'
complete -c knock -s v -l verbose -d 'Output verbose status messages'
complete -c knock -s V -l version -d 'Display the version'
complete -c knock -s h -l help -d 'Syntax help.  EXAMPLES'

