# ldns-nsec3-hash
# Autogenerated from man page /opt/homebrew/share/man/man1/ldns-nsec3-hash.1
complete -c ldns-nsec3-hash -s a -d 'Use the given algorithm number for the hash calculation'
complete -c ldns-nsec3-hash -s s -d 'Use the given salt for the hash calculation'
complete -c ldns-nsec3-hash -s t -d 'Use count iterations for the hash calculation'

