# ldns-test-edns
# Autogenerated from man page /opt/homebrew/share/man/man1/ldns-test-edns.1
complete -c ldns-test-edns -s i -d 'after another, with no other explanations, and if none work or no IP addresse…'

