# ldns-zsplit
# Autogenerated from man page /opt/homebrew/share/man/man1/ldns-zsplit.1
complete -c ldns-zsplit -s n -d 'Split after NUMBER RRs, ldns-zsplit will not split in the middle of an RRs'
complete -c ldns-zsplit -s o -d 'use ORIGIN as origin when reading the zonefile'
complete -c ldns-zsplit -s z -d 'Sort the zone before splitting'
complete -c ldns-zsplit -s v -d 'Show version number and exit'

