# metal-lipo
# Autogenerated from man page /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/metal-lipo.1
complete -c metal-lipo -o help -s h -d 'Display usage information and exit'
complete -c metal-lipo -o version -d 'Display the version of this program'
complete -c metal-lipo -o verify_arch -d 'Take a single input file and verify the specified architectures are present i…'
complete -c metal-lipo -o archs -d 'Take a single input file and display the architectures present in the file'
complete -c metal-lipo -o info -d 'Take at least one input file and display the descriptions of each file'
complete -c metal-lipo -o thin -d 'Take a single universal binary input file and the thin flag followed by an ar…'
complete -c metal-lipo -o create -d 'Take at least one input file and require the output flag to be specified'
complete -c metal-lipo -o replace -d 'Take a single universal binary input file and require the output flag to be s…'
complete -c metal-lipo -o segalign -d 'Additional flag that can be specified with create and replace'

