# metal-source
# Autogenerated from man page /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/metal-source.1
complete -c metal-source -o help -s h -d 'Display usage information and exit'
complete -c metal-source -o version -d 'Display the version of this program'
complete -c metal-source -o arch -d 'Specify the architecture to dump'
complete -c metal-source -o extract -d 'Choose the format of the extracted information'
complete -c metal-source -s f -d 'Overwrite output path'
complete -c metal-source -o flatbuffers -d 'Choose how to format extracted flatbuffers'
complete -c metal-source -s o -d 'Specify the directory where write the extracted source information'
complete -c metal-source -s v -d 'Enable verbose output'

