# metal-pack
# Autogenerated from man page /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/metal-pack.1
complete -c metal-pack -o help -s h -d 'Display usage information and exit'
complete -c metal-pack -o version -d 'Display the version of this program'
complete -c metal-pack -o pack-metallibs -d 'Set the metallibs packing policy to none, internal, or external'
complete -c metal-pack -o pack-descriptors -d 'Set the descriptors packing policy to none, internal, or external'
complete -c metal-pack -o pack-reflections -d 'Set the reflections packing policy to none, internal, or external'
complete -c metal-pack -s o -d 'Set the output file name'
complete -c metal-pack -o nthreads -d 'Perform optimization using n threads'
complete -c metal-pack -o stats -d 'Display statistics about packed inputs'

