# mono-cil-strip
# Autogenerated from man page /usr/local/share/man/man1/mono-cil-strip.1
complete -c mono-cil-strip -s q -d 'Only output errors.  COPYRIGHT Copyright (C) 2008 Novell, Inc (http://www'

