# mysqldump
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/mysqldump.1
complete -c mysqldump -l single-transaction -d 'option is not used'
complete -c mysqldump -l result-file -d 'option, which creates the output in ASCII format: shell> mysqldump [options] …'
complete -c mysqldump -l quick -d 'option (or'
complete -c mysqldump -l opt
complete -c mysqldump -l skip-quick
complete -c mysqldump -l skip-opt -d 'option instead of the'
complete -c mysqldump -l extended-insert -d option
complete -c mysqldump -l databases -d or
complete -c mysqldump -l all-databases -d option
complete -c mysqldump -l bind-address
complete -c mysqldump -l compress
complete -c mysqldump -s C
complete -c mysqldump -l default-auth
complete -c mysqldump -l enable-cleartext-plugin
complete -c mysqldump -l get-server-public-key
complete -c mysqldump -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqldump -l host
complete -c mysqldump -s h
complete -c mysqldump -l login-path
complete -c mysqldump -l password
complete -c mysqldump -s p
complete -c mysqldump -l pipe
complete -c mysqldump -s W
complete -c mysqldump -l plugin-dir
complete -c mysqldump -l port
complete -c mysqldump -s P
complete -c mysqldump -l protocol
complete -c mysqldump -l secure-auth
complete -c mysqldump -l socket
complete -c mysqldump -s S
complete -c mysqldump -l 'ssl*'
complete -c mysqldump -l ssl -d 'specify whether to connect to the server using SSL and indicate where to find…'
complete -c mysqldump -l tls-version
complete -c mysqldump -l user
complete -c mysqldump -s u
complete -c mysqldump -l var_name -d 'syntax: oc o 2. 3'
complete -c mysqldump -l defaults-extra-file
complete -c mysqldump -l defaults-file
complete -c mysqldump -l defaults-group-suffix
complete -c mysqldump -l no-defaults
complete -c mysqldump -l print-defaults
complete -c mysqldump -l add-drop-database
complete -c mysqldump -l add-drop-table
complete -c mysqldump -l add-drop-trigger
complete -c mysqldump -l all-tablespaces
complete -c mysqldump -s Y
complete -c mysqldump -l no-create-db
complete -c mysqldump -s n
complete -c mysqldump -l no-create-info
complete -c mysqldump -s t
complete -c mysqldump -l no-tablespaces -d 'option for this purpose.  oc o 2. 3'
complete -c mysqldump -s y
complete -c mysqldump -l replace
complete -c mysqldump -l allow-keywords
complete -c mysqldump -l comments
complete -c mysqldump -s i
complete -c mysqldump -l skip-comments -d 'oc o 2. 3'
complete -c mysqldump -l debug
complete -c mysqldump -s '#'
complete -c mysqldump -l debug-check
complete -c mysqldump -l debug-info
complete -c mysqldump -l dump-date
complete -c mysqldump -l skip-dump-date -d 'control whether the date is added to the comment.  The default is'
complete -c mysqldump -l force
complete -c mysqldump -s f
complete -c mysqldump -l ignore-error -d 'option is also given to ignore specific errors,'
complete -c mysqldump -l log-error
complete -c mysqldump -l verbose
complete -c mysqldump -s v
complete -c mysqldump -l help
complete -c mysqldump -s '?'
complete -c mysqldump -l version
complete -c mysqldump -s V
complete -c mysqldump -l character-sets-dir
complete -c mysqldump -l default-character-set
complete -c mysqldump -l no-set-names
complete -c mysqldump -s N
complete -c mysqldump -l set-charset -d 'setting, the same as specifying'
complete -c mysqldump -l skip-set-charset -d 'oc o 2. 3'
complete -c mysqldump -l apply-slave-statements
complete -c mysqldump -l dump-slave -d 'option, add a STOP SLAVE statement before the CHANGE MASTER TO statement and …'
complete -c mysqldump -l delete-master-logs
complete -c mysqldump -l master-data -d 'oc o 2. 3'
complete -c mysqldump -l include-master-host-port -d 'options can also be used.  oc o 2. 3'
complete -c mysqldump -l lock-tables
complete -c mysqldump -l lock-all-tables
complete -c mysqldump -l set-gtid-purged
complete -c mysqldump -l compact
complete -c mysqldump -l skip-add-drop-table
complete -c mysqldump -l skip-add-locks
complete -c mysqldump -l skip-disable-keys
complete -c mysqldump -l compatible
complete -c mysqldump -l complete-insert
complete -c mysqldump -s c
complete -c mysqldump -l create-options
complete -c mysqldump -l fields-terminated-by
complete -c mysqldump -l fields-enclosed-by
complete -c mysqldump -l fields-optionally-enclosed-by
complete -c mysqldump -l fields-escaped-by
complete -c mysqldump -l tab -d 'option and have the same meaning as the corresponding FIELDS clauses for LOAD…'
complete -c mysqldump -l hex-blob
complete -c mysqldump -l lines-terminated-by
complete -c mysqldump -l quote-names
complete -c mysqldump -s Q
complete -c mysqldump -l skip-quote-names
complete -c mysqldump -s r
complete -c mysqldump -s T
complete -c mysqldump -l fields-xxx -d and
complete -c mysqldump -l tz-utc
complete -c mysqldump -l skip-tz-utc -d 'oc o 2. 3'
complete -c mysqldump -l xml
complete -c mysqldump -s X
complete -c mysqldump -s A
complete -c mysqldump -s B
complete -c mysqldump -l skip-lock-tables -d 'option. ) oc o 2. 3'
complete -c mysqldump -l events
complete -c mysqldump -s E
complete -c mysqldump -l ignore-table
complete -c mysqldump -l no-data
complete -c mysqldump -s d
complete -c mysqldump -l routines
complete -c mysqldump -s R
complete -c mysqldump -l tables
complete -c mysqldump -l triggers
complete -c mysqldump -l skip-triggers
complete -c mysqldump -l where
complete -c mysqldump -s w
complete -c mysqldump -l disable-keys
complete -c mysqldump -s K
complete -c mysqldump -s e
complete -c mysqldump -l insert-ignore
complete -c mysqldump -l add-locks
complete -c mysqldump -s q
complete -c mysqldump -l flush-logs
complete -c mysqldump -s F
complete -c mysqldump -l flush-privileges
complete -c mysqldump -s x
complete -c mysqldump -s l
complete -c mysqldump -l no-autocommit
complete -c mysqldump -l order-by-primary
complete -c mysqldump -l shared-memory-base-name
complete -c mysqldump -l shared-memory -d 'option to enable shared-memory connections.  oc o 2. 3'
complete -c mysqldump -l skip-compact -d form
complete -c mysqldump -l skip -d 'option for each feature'
complete -c mysqldump -l skip-extended-insert

