# mysql
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/mysql.1
complete -c mysql -l quick -d option
complete -c mysql -l help
complete -c mysql -s '?'
complete -c mysql -l auto-rehash
complete -c mysql -l disable-auto-rehash -d 'to disable rehashing'
complete -c mysql -l auto-vertical-output
complete -c mysql -l batch
complete -c mysql -s B
complete -c mysql -l raw -d 'option.  oc o 2. 3'
complete -c mysql -l binary-as-hex
complete -c mysql -l binary-mode
complete -c mysql -l bind-address
complete -c mysql -l character-sets-dir
complete -c mysql -l column-names
complete -c mysql -l column-type-info
complete -c mysql -l comments
complete -c mysql -s c
complete -c mysql -l skip-comments -d '(strip comments), enable with'
complete -c mysql -l compress
complete -c mysql -s C
complete -c mysql -l connect-expired-password
complete -c mysql -l database
complete -c mysql -s D
complete -c mysql -l debug
complete -c mysql -s '#'
complete -c mysql -l debug-check
complete -c mysql -l debug-info
complete -c mysql -s T
complete -c mysql -l default-auth
complete -c mysql -l default-character-set
complete -c mysql -l defaults-extra-file
complete -c mysql -l defaults-file
complete -c mysql -l defaults-group-suffix
complete -c mysql -l delimiter
complete -c mysql -l disable-named-commands
complete -c mysql -l enable-cleartext-plugin
complete -c mysql -l execute
complete -c mysql -s e
complete -c mysql -l force
complete -c mysql -s f
complete -c mysql -l get-server-public-key
complete -c mysql -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysql -l histignore
complete -c mysql -l syslog -d 'option is given'
complete -c mysql -l host
complete -c mysql -s h
complete -c mysql -l html
complete -c mysql -s H
complete -c mysql -l ignore-spaces
complete -c mysql -s i
complete -c mysql -l init-command
complete -c mysql -l line-numbers
complete -c mysql -l skip-line-numbers -d 'oc o 2. 3'
complete -c mysql -l local-infile
complete -c mysql -l login-path
complete -c mysql -l named-commands
complete -c mysql -s G
complete -c mysql -l skip-named-commands -d 'to disable named commands.  See the section called “MYSQL COMMANDS”.  oc o 2'
complete -c mysql -l no-auto-rehash
complete -c mysql -s A
complete -c mysql -l skip-auto-rehash
complete -c mysql -l no-beep
complete -c mysql -s b
complete -c mysql -l no-defaults
complete -c mysql -l one-database
complete -c mysql -s o
complete -c mysql -l pager
complete -c mysql -l skip-pager -d 'the section called “MYSQL COMMANDS”, discusses output paging further.  oc o 2'
complete -c mysql -l password
complete -c mysql -s p
complete -c mysql -l pipe
complete -c mysql -s W
complete -c mysql -l plugin-dir
complete -c mysql -l port
complete -c mysql -s P
complete -c mysql -l print-defaults
complete -c mysql -l prompt
complete -c mysql -l protocol
complete -c mysql -s q
complete -c mysql -s r
complete -c mysql -l silent -d 'option is given), special characters are escaped in the output so they can be…'
complete -c mysql -l reconnect
complete -c mysql -l skip-reconnect -d 'oc o 2. 3'
complete -c mysql -l safe-updates
complete -c mysql -l i-am-a-dummy
complete -c mysql -s U
complete -c mysql -l skip-safe-updates -d 'on the command line to override it'
complete -c mysql -l secure-auth
complete -c mysql -l shared-memory-base-name
complete -c mysql -l shared-memory -d 'option to enable shared-memory connections.  oc o 2. 3'
complete -c mysql -l show-warnings
complete -c mysql -l sigint-ignore
complete -c mysql -s s
complete -c mysql -l skip-column-names
complete -c mysql -s N
complete -c mysql -s L
complete -c mysql -l socket
complete -c mysql -s S
complete -c mysql -l 'ssl*'
complete -c mysql -l ssl -d 'specify whether to connect to the server using SSL and indicate where to find…'
complete -c mysql -s j
complete -c mysql -l table
complete -c mysql -s t
complete -c mysql -l tee
complete -c mysql -l tls-version
complete -c mysql -l unbuffered
complete -c mysql -s n
complete -c mysql -l user
complete -c mysql -s u
complete -c mysql -l verbose
complete -c mysql -s v
complete -c mysql -l version
complete -c mysql -s V
complete -c mysql -l vertical
complete -c mysql -s E
complete -c mysql -l wait
complete -c mysql -s w
complete -c mysql -l xml
complete -c mysql -s X
complete -c mysql -l var_name -d 'oc o 2. 3'
complete -c mysql -s F -d and
complete -c mysql -l select_limit -d and
complete -c mysql -l max_join_size -d 'options when you invoke mysql: mysql --safe-updates --select_limit=500 --max_…'

