# mysqld_multi
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/mysqld_multi.1
complete -c mysqld_multi -l defaults-file -d 'option).  N can be any positive integer'
complete -c mysqld_multi -l no-defaults -d 'oc o 2. 3'
complete -c mysqld_multi -l defaults-extra-file -d 'option, if one is given'
complete -c mysqld_multi -l help
complete -c mysqld_multi -l example
complete -c mysqld_multi -l log
complete -c mysqld_multi -l mysqladmin
complete -c mysqld_multi -l mysqld
complete -c mysqld_multi -l no-log
complete -c mysqld_multi -l password
complete -c mysqld_multi -l silent
complete -c mysqld_multi -l tcp-ip
complete -c mysqld_multi -l user
complete -c mysqld_multi -l verbose
complete -c mysqld_multi -l version
complete -c mysqld_multi -l bind-address -d 'to cause different servers to listen to different interfaces. ) oc o 2. 3'
complete -c mysqld_multi -l pid-file -d 'option is very important if you are using mysqld_safe to start mysqld (for ex…'

