# mysqlshow
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/mysqlshow.1
complete -c mysqlshow -l help
complete -c mysqlshow -s '?'
complete -c mysqlshow -l bind-address
complete -c mysqlshow -l character-sets-dir
complete -c mysqlshow -l compress
complete -c mysqlshow -s C
complete -c mysqlshow -l count
complete -c mysqlshow -l debug
complete -c mysqlshow -s '#'
complete -c mysqlshow -l debug-check
complete -c mysqlshow -l debug-info
complete -c mysqlshow -l default-character-set
complete -c mysqlshow -l default-auth
complete -c mysqlshow -l defaults-extra-file
complete -c mysqlshow -l defaults-file
complete -c mysqlshow -l defaults-group-suffix
complete -c mysqlshow -l enable-cleartext-plugin
complete -c mysqlshow -l get-server-public-key
complete -c mysqlshow -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlshow -l host
complete -c mysqlshow -s h
complete -c mysqlshow -l keys
complete -c mysqlshow -s k
complete -c mysqlshow -l login-path
complete -c mysqlshow -l no-defaults
complete -c mysqlshow -l password
complete -c mysqlshow -s p
complete -c mysqlshow -l pipe
complete -c mysqlshow -s W
complete -c mysqlshow -l plugin-dir
complete -c mysqlshow -l port
complete -c mysqlshow -s P
complete -c mysqlshow -l print-defaults
complete -c mysqlshow -l protocol
complete -c mysqlshow -l secure-auth
complete -c mysqlshow -l shared-memory-base-name
complete -c mysqlshow -l shared-memory -d 'option to enable shared-memory connections.  oc o 2. 3'
complete -c mysqlshow -l show-table-type
complete -c mysqlshow -s t
complete -c mysqlshow -l socket
complete -c mysqlshow -s S
complete -c mysqlshow -l 'ssl*'
complete -c mysqlshow -l ssl -d 'specify whether to connect to the server using SSL and indicate where to find…'
complete -c mysqlshow -l status
complete -c mysqlshow -s i
complete -c mysqlshow -l tls-version
complete -c mysqlshow -l user
complete -c mysqlshow -s u
complete -c mysqlshow -l verbose
complete -c mysqlshow -s v
complete -c mysqlshow -l version
complete -c mysqlshow -s V

