# mysqlpump
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/mysqlpump.1
complete -c mysqlpump -l single-transaction -d 'option is not used'
complete -c mysqlpump -l result-file -d 'option, which creates the output in ASCII format: shell> mysqlpump [options] …'
complete -c mysqlpump -l all-databases -d 'option: shell> mysqlpump --all-databases To dump a single database, or certai…'
complete -c mysqlpump -l databases -d 'option: shell> mysqlpump --databases db_name1 db_name2 '
complete -c mysqlpump -l users -d 'option and suppress all database dumping: shell> mysqlpump --exclude-database…'
complete -c mysqlpump -l exclude-databases -d option
complete -c mysqlpump -l help
complete -c mysqlpump -s '?'
complete -c mysqlpump -l add-drop-database
complete -c mysqlpump -l add-drop-table
complete -c mysqlpump -l add-drop-user
complete -c mysqlpump -l add-locks
complete -c mysqlpump -s A
complete -c mysqlpump -l bind-address
complete -c mysqlpump -l character-sets-dir
complete -c mysqlpump -l complete-insert
complete -c mysqlpump -l compress
complete -c mysqlpump -s C
complete -c mysqlpump -l compress-output
complete -c mysqlpump -s B
complete -c mysqlpump -l debug
complete -c mysqlpump -s '#'
complete -c mysqlpump -l debug-check
complete -c mysqlpump -l debug-info
complete -c mysqlpump -s T
complete -c mysqlpump -l default-auth
complete -c mysqlpump -l default-character-set
complete -c mysqlpump -l default-parallelism
complete -c mysqlpump -l parallel-schemas -d 'option also affects parallelism and can be used to override the default numbe…'
complete -c mysqlpump -l defaults-extra-file
complete -c mysqlpump -l defaults-file
complete -c mysqlpump -l defaults-group-suffix
complete -c mysqlpump -l defer-table-indexes
complete -c mysqlpump -l skip-defer-table-indexes -d 'to disable it.  oc o 2. 3'
complete -c mysqlpump -l events
complete -c mysqlpump -l skip-events -d 'to disable it.  oc o 2. 3'
complete -c mysqlpump -l exclude-events
complete -c mysqlpump -l exclude-routines
complete -c mysqlpump -l exclude-tables
complete -c mysqlpump -l exclude-triggers
complete -c mysqlpump -l exclude-users
complete -c mysqlpump -l extended-insert
complete -c mysqlpump -l get-server-public-key
complete -c mysqlpump -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlpump -l hex-blob
complete -c mysqlpump -l host
complete -c mysqlpump -s h
complete -c mysqlpump -l include-databases
complete -c mysqlpump -l include-events
complete -c mysqlpump -l include-routines
complete -c mysqlpump -l include-tables
complete -c mysqlpump -l include-triggers
complete -c mysqlpump -l include-users
complete -c mysqlpump -l insert-ignore
complete -c mysqlpump -l log-error-file
complete -c mysqlpump -l login-path
complete -c mysqlpump -l max-allowed-packet
complete -c mysqlpump -l net-buffer-length
complete -c mysqlpump -l no-create-db
complete -c mysqlpump -l no-create-info
complete -c mysqlpump -s t
complete -c mysqlpump -l no-defaults
complete -c mysqlpump -l password
complete -c mysqlpump -s p
complete -c mysqlpump -l plugin-dir
complete -c mysqlpump -l port
complete -c mysqlpump -s P
complete -c mysqlpump -l print-defaults
complete -c mysqlpump -l protocol
complete -c mysqlpump -l replace
complete -c mysqlpump -l routines
complete -c mysqlpump -l skip-routines -d 'to disable it.  oc o 2. 3'
complete -c mysqlpump -l secure-auth
complete -c mysqlpump -l set-charset
complete -c mysqlpump -l skip-set-charset -d 'oc o 2. 3'
complete -c mysqlpump -l set-gtid-purged
complete -c mysqlpump -l skip-definer
complete -c mysqlpump -l skip-dump-rows
complete -c mysqlpump -s d
complete -c mysqlpump -l socket
complete -c mysqlpump -s S
complete -c mysqlpump -l 'ssl*'
complete -c mysqlpump -l ssl -d 'specify whether to connect to the server using SSL and indicate where to find…'
complete -c mysqlpump -l tls-version
complete -c mysqlpump -l triggers
complete -c mysqlpump -l skip-triggers -d 'to disable it.  oc o 2. 3'
complete -c mysqlpump -l tz-utc
complete -c mysqlpump -l skip-tz-utc -d 'to disable it.  oc o 2. 3'
complete -c mysqlpump -l user
complete -c mysqlpump -s u
complete -c mysqlpump -l version
complete -c mysqlpump -s V
complete -c mysqlpump -l watch-progress
complete -c mysqlpump -l skip-watch-progress -d 'to disable it'

