# mysql_config_editor
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/mysql_config_editor.1
complete -c mysql_config_editor -l login-path -d 'option to indicate explicitly which login path to use.  oc o 2. 3'
complete -c mysql_config_editor -l no-defaults -d 'option is used'
complete -c mysql_config_editor -l all -d 'to display all login paths or'
complete -c mysql_config_editor -l help
complete -c mysql_config_editor -s '?'
complete -c mysql_config_editor -l debug
complete -c mysql_config_editor -s '#'
complete -c mysql_config_editor -l verbose
complete -c mysql_config_editor -s v
complete -c mysql_config_editor -l version
complete -c mysql_config_editor -s V
complete -c mysql_config_editor -s G
complete -c mysql_config_editor -l host
complete -c mysql_config_editor -l password
complete -c mysql_config_editor -l port
complete -c mysql_config_editor -l socket
complete -c mysql_config_editor -l user -d options
complete -c mysql_config_editor -s h
complete -c mysql_config_editor -s p
complete -c mysql_config_editor -s P
complete -c mysql_config_editor -s S
complete -c mysql_config_editor -s u
complete -c mysql_config_editor -l warn
complete -c mysql_config_editor -s w
complete -c mysql_config_editor -l skip-warn -d 'to disable it.  oc o 2. 3'

