# mysqlimport
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/mysqlimport.1
complete -c mysqlimport -l help
complete -c mysqlimport -s '?'
complete -c mysqlimport -l bind-address
complete -c mysqlimport -l character-sets-dir
complete -c mysqlimport -l columns
complete -c mysqlimport -s c
complete -c mysqlimport -l compress
complete -c mysqlimport -s C
complete -c mysqlimport -l debug
complete -c mysqlimport -s '#'
complete -c mysqlimport -l debug-check
complete -c mysqlimport -l debug-info
complete -c mysqlimport -l default-character-set
complete -c mysqlimport -l default-auth
complete -c mysqlimport -l defaults-extra-file
complete -c mysqlimport -l defaults-file
complete -c mysqlimport -l defaults-group-suffix
complete -c mysqlimport -l delete
complete -c mysqlimport -s D
complete -c mysqlimport -l enable-cleartext-plugin
complete -c mysqlimport -l fields-terminated-by
complete -c mysqlimport -l fields-enclosed-by
complete -c mysqlimport -l fields-optionally-enclosed-by
complete -c mysqlimport -l fields-escaped-by
complete -c mysqlimport -l force
complete -c mysqlimport -s f
complete -c mysqlimport -l get-server-public-key
complete -c mysqlimport -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqlimport -l host
complete -c mysqlimport -s h
complete -c mysqlimport -l ignore
complete -c mysqlimport -s i
complete -c mysqlimport -l replace -d 'option.  oc o 2. 3'
complete -c mysqlimport -l ignore-lines
complete -c mysqlimport -l lines-terminated-by
complete -c mysqlimport -l local
complete -c mysqlimport -s L
complete -c mysqlimport -l lock-tables
complete -c mysqlimport -s l
complete -c mysqlimport -l login-path
complete -c mysqlimport -l low-priority
complete -c mysqlimport -l no-defaults
complete -c mysqlimport -l password
complete -c mysqlimport -s p
complete -c mysqlimport -l pipe
complete -c mysqlimport -s W
complete -c mysqlimport -l plugin-dir
complete -c mysqlimport -l port
complete -c mysqlimport -s P
complete -c mysqlimport -l print-defaults
complete -c mysqlimport -l protocol
complete -c mysqlimport -s r
complete -c mysqlimport -l secure-auth
complete -c mysqlimport -l shared-memory-base-name
complete -c mysqlimport -l shared-memory -d 'option to enable shared-memory connections.  oc o 2. 3'
complete -c mysqlimport -l silent
complete -c mysqlimport -s s
complete -c mysqlimport -l socket
complete -c mysqlimport -s S
complete -c mysqlimport -l 'ssl*'
complete -c mysqlimport -l ssl -d 'specify whether to connect to the server using SSL and indicate where to find…'
complete -c mysqlimport -l tls-version
complete -c mysqlimport -l user
complete -c mysqlimport -s u
complete -c mysqlimport -l use-threads
complete -c mysqlimport -l verbose
complete -c mysqlimport -s v
complete -c mysqlimport -l version
complete -c mysqlimport -s V

