# mysql_secure_installation
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/mysql_secure_installation.1
complete -c mysql_secure_installation -l host -d and
complete -c mysql_secure_installation -l port -d 'can be used on the command line and in option files'
complete -c mysql_secure_installation -l help
complete -c mysql_secure_installation -s '?'
complete -c mysql_secure_installation -l defaults-extra-file
complete -c mysql_secure_installation -l defaults-file
complete -c mysql_secure_installation -l defaults-group-suffix
complete -c mysql_secure_installation -s h
complete -c mysql_secure_installation -l no-defaults
complete -c mysql_secure_installation -l password
complete -c mysql_secure_installation -s p
complete -c mysql_secure_installation -s P
complete -c mysql_secure_installation -l print-defaults
complete -c mysql_secure_installation -l protocol
complete -c mysql_secure_installation -l socket
complete -c mysql_secure_installation -s S
complete -c mysql_secure_installation -l 'ssl*'
complete -c mysql_secure_installation -l ssl -d 'specify whether to connect to the server using SSL and indicate where to find…'
complete -c mysql_secure_installation -l tls-version
complete -c mysql_secure_installation -l use-default
complete -c mysql_secure_installation -l user
complete -c mysql_secure_installation -s u

