# mysql_upgrade
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/mysql_upgrade.1
complete -c mysql_upgrade -l early-plugin-load -d 'value is empty.  To load the keyring_file plugin, you must use an explicit'
complete -c mysql_upgrade -l protocol -d 'option forces a connection using TCP/IP rather than the Unix socket file'
complete -c mysql_upgrade -l force -d option
complete -c mysql_upgrade -l skip-sys-schema -d 'option, mysql_upgrade installs the sys schema if it is not installed, and upg…'
complete -c mysql_upgrade -l help
complete -c mysql_upgrade -l basedir
complete -c mysql_upgrade -l bind-address
complete -c mysql_upgrade -l character-sets-dir
complete -c mysql_upgrade -l compress
complete -c mysql_upgrade -s C
complete -c mysql_upgrade -l datadir
complete -c mysql_upgrade -l debug
complete -c mysql_upgrade -s '#'
complete -c mysql_upgrade -l debug-check
complete -c mysql_upgrade -l debug-info
complete -c mysql_upgrade -s T
complete -c mysql_upgrade -l default-auth
complete -c mysql_upgrade -l default-character-set
complete -c mysql_upgrade -l defaults-extra-file
complete -c mysql_upgrade -l defaults-file
complete -c mysql_upgrade -l defaults-group-suffix
complete -c mysql_upgrade -l host
complete -c mysql_upgrade -s h
complete -c mysql_upgrade -l login-path
complete -c mysql_upgrade -l max-allowed-packet
complete -c mysql_upgrade -l net-buffer-length
complete -c mysql_upgrade -l no-defaults
complete -c mysql_upgrade -l password
complete -c mysql_upgrade -s p
complete -c mysql_upgrade -l pipe
complete -c mysql_upgrade -s W
complete -c mysql_upgrade -l plugin-dir
complete -c mysql_upgrade -l port
complete -c mysql_upgrade -s P
complete -c mysql_upgrade -l print-defaults
complete -c mysql_upgrade -l shared-memory-base-name
complete -c mysql_upgrade -l shared-memory -d 'option to enable shared-memory connections.  oc o 2. 3'
complete -c mysql_upgrade -l socket
complete -c mysql_upgrade -s S
complete -c mysql_upgrade -l 'ssl*'
complete -c mysql_upgrade -l ssl -d 'specify whether to connect to the server using SSL and indicate where to find…'
complete -c mysql_upgrade -l tls-version
complete -c mysql_upgrade -l tmpdir
complete -c mysql_upgrade -s t
complete -c mysql_upgrade -l upgrade-system-tables
complete -c mysql_upgrade -s s
complete -c mysql_upgrade -l user
complete -c mysql_upgrade -s u
complete -c mysql_upgrade -l verbose
complete -c mysql_upgrade -l version-check
complete -c mysql_upgrade -s k
complete -c mysql_upgrade -l skip-version-check -d 'oc o 2. 3'
complete -c mysql_upgrade -l write-binlog

