# mysqladmin
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/mysqladmin.1
complete -c mysqladmin -l skip-grant-tables -d 'option.  No password change will be applied'
complete -c mysqladmin -l verbose -d 'option is given, the output is like that of SHOW FULL PROCESSLIST'
complete -c mysqladmin -l help
complete -c mysqladmin -s '?'
complete -c mysqladmin -l bind-address
complete -c mysqladmin -l character-sets-dir
complete -c mysqladmin -l compress
complete -c mysqladmin -s C
complete -c mysqladmin -l count
complete -c mysqladmin -s c
complete -c mysqladmin -l sleep -d 'option is given.  oc o 2. 3'
complete -c mysqladmin -l debug
complete -c mysqladmin -s '#'
complete -c mysqladmin -l debug-check
complete -c mysqladmin -l debug-info
complete -c mysqladmin -l default-auth
complete -c mysqladmin -l default-character-set
complete -c mysqladmin -l defaults-extra-file
complete -c mysqladmin -l defaults-file
complete -c mysqladmin -l defaults-group-suffix
complete -c mysqladmin -l enable-cleartext-plugin
complete -c mysqladmin -l force
complete -c mysqladmin -s f
complete -c mysqladmin -l get-server-public-key
complete -c mysqladmin -l server-public-key-path -d 'is given and specifies a valid public key file, it takes precedence over'
complete -c mysqladmin -l host
complete -c mysqladmin -s h
complete -c mysqladmin -l login-path
complete -c mysqladmin -l no-beep
complete -c mysqladmin -s b
complete -c mysqladmin -l no-defaults
complete -c mysqladmin -l password
complete -c mysqladmin -s p
complete -c mysqladmin -l pipe
complete -c mysqladmin -s W
complete -c mysqladmin -l plugin-dir
complete -c mysqladmin -l port
complete -c mysqladmin -s P
complete -c mysqladmin -l print-defaults
complete -c mysqladmin -l protocol
complete -c mysqladmin -l relative
complete -c mysqladmin -s r
complete -c mysqladmin -l show-warnings
complete -c mysqladmin -l secure-auth
complete -c mysqladmin -l shared-memory-base-name
complete -c mysqladmin -l shared-memory -d 'option to enable shared-memory connections.  oc o 2. 3'
complete -c mysqladmin -l silent
complete -c mysqladmin -s s
complete -c mysqladmin -s i
complete -c mysqladmin -l socket
complete -c mysqladmin -s S
complete -c mysqladmin -l 'ssl*'
complete -c mysqladmin -l ssl -d 'specify whether to connect to the server using SSL and indicate where to find…'
complete -c mysqladmin -l tls-version
complete -c mysqladmin -l user
complete -c mysqladmin -s u
complete -c mysqladmin -s v
complete -c mysqladmin -l version
complete -c mysqladmin -s V
complete -c mysqladmin -l vertical
complete -c mysqladmin -s E
complete -c mysqladmin -l wait
complete -c mysqladmin -s w
complete -c mysqladmin -l var_name -d 'oc o 2. 3'

