# pcre2grep
# Autogenerated from man page /opt/homebrew/share/man/man1/pcre2grep.1
complete -c pcre2grep -l allow-lookaround-bsk -d 'PCRE2 now forbids the use of K in lookarounds by default, in line with Perl'
complete -c pcre2grep -s Z -l null -d 'Terminate files names in the regular output with a zero byte (the NUL charact…'

