# pdffonts
# Autogenerated from man page /opt/homebrew/share/man/man1/pdffonts.1
complete -c pdffonts -s f -d 'Specifies the first page to analyze'
complete -c pdffonts -o loc -d 'Shows additional information on the location of the font that will be used wh…'
complete -c pdffonts -o locPS -d 'Shows additional information on the location of the font that will be used wh…'
complete -c pdffonts -s l -d 'Specifies the last page to analyze'
complete -c pdffonts -o opw -d 'Specify the owner password for the PDF file'
complete -c pdffonts -o upw -d 'Specify the user password for the PDF file'
complete -c pdffonts -o cfg -d 'Read  config-file in place of ~/. xpdfrc or the system-wide config file'
complete -c pdffonts -s v -d 'Print copyright and version information'
complete -c pdffonts -s h -d 'Print usage information.  ( -help and'
complete -c pdffonts -l help -d 'are equivalent. ) EXIT CODES The Xpdf tools use the following exit codes:'

