# pdfinfo
# Autogenerated from man page /opt/homebrew/share/man/man1/pdfinfo.1
complete -c pdfinfo -s f -d 'Specifies the first page to examine'
complete -c pdfinfo -s l -d 'Specifies the last page to examine'
complete -c pdfinfo -o box -d 'Prints the page box bounding boxes: MediaBox, CropBox, BleedBox, TrimBox, and…'
complete -c pdfinfo -o meta -d 'Prints document-level metadata'
complete -c pdfinfo -o rawdates -d 'Prints the raw (undecoded) date strings, directly from the PDF file'
complete -c pdfinfo -o enc -d 'Sets the encoding to use for text output'
complete -c pdfinfo -o opw -d 'Specify the owner password for the PDF file'
complete -c pdfinfo -o upw -d 'Specify the user password for the PDF file'
complete -c pdfinfo -o cfg -d 'Read  config-file in place of ~/. xpdfrc or the system-wide config file'
complete -c pdfinfo -s v -d 'Print copyright and version information'
complete -c pdfinfo -s h -d 'Print usage information.  ( -help and'
complete -c pdfinfo -l help -d 'are equivalent. ) EXIT CODES The Xpdf tools use the following exit codes:'

