# pwsh
# Autogenerated from man page /usr/local/share/man/man1/pwsh.1.gz
complete -c pwsh -o NoLogo -d 'Hides the copyright banner at startup'
complete -c pwsh -o NoExit -d 'Does not exit after running startup commands'
complete -c pwsh -o NoProfile -d 'Does not load the PowerShell profile'
complete -c pwsh -o NonInteractive -d 'Does not present an interactive prompt to the user'
complete -c pwsh -o InputFormat -d 'Describes the format of data sent to PowerShell'
complete -c pwsh -o OutputFormat -d 'Determines how output from PowerShell is formatted'
complete -c pwsh -o EncodedCommand -d 'Accepts a base-64-encoded string version of a command'
complete -c pwsh -o File -d 'Runs the specified script in the local scope ("dot-sourced"), so that the fun…'
complete -c pwsh -o ExecutionPolicy -d 'Sets the default execution policy for the current session and saves it in the…'
complete -c pwsh -o Command -d 'Executes the specified commands (and any parameters) as though they were type…'

