# replace
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/replace.1
complete -c replace -s '?'
complete -c replace -s I
complete -c replace -o '#debug_options'
complete -c replace -s s
complete -c replace -s v
complete -c replace -s V

