# sasldblistusers2
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man8/sasldblistusers2.8
complete -c sasldblistusers2 -s f -d 'use  file for sasldb'
complete -c sasldblistusers2 -s v -d 'Print libsasl2 version number and exit.  SEE ALSO saslpasswd2(8)'

