# setreg
# Autogenerated from man page /usr/local/share/man/man1/setreg.1
complete -c setreg -s q -d 'Quiet mode.  Limited display on console'
complete -c setreg -o help -s h -s '?' -d 'Display help about this tool.  FEATURES'

