# showfont
# Autogenerated from man page /opt/X11/share/man/man1/showfont.1
complete -c showfont -o server -d 'The X font server to contact'
complete -c showfont -o fn -d 'The font to display'
complete -c showfont -o lsb -d 'The bit order of the font should be requested as LSBFirst (least significant …'
complete -c showfont -o msb -d 'The bit order of the font should be requested as MSBFirst (most significant b…'
complete -c showfont -o LSB -d 'The byte order of the font should be requested as LSBFirst (least significant…'
complete -c showfont -o MSB -d 'The byte order of the font should be requested as MSBFirst (most significant …'
complete -c showfont -o ext -d 'Only the character extents should be displayed, but not the bitmaps'
complete -c showfont -o start -d 'The start of the range of the characters to display (char is a number)'
complete -c showfont -o end -d 'The end of the range of the characters to display (char is a number)'
complete -c showfont -o unit -d 'The scanline unit of the font (8, 16, 32, or 64)'
complete -c showfont -o pad -d 'The scanpad unit of the font (8, 16, 32, or 64)'
complete -c showfont -s b -d 'The bitmap padding unit of the font (0, 1, or 2, where 0 is ImageRectMin, 1 i…'
complete -c showfont -o noprops -d 'Do not show the font properties'

