# solv
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/solv.1
complete -c solv -l root
complete -c solv -l clean
complete -c solv -l best
complete -c solv -l testcase
complete -c solv -s i
complete -c solv -s r
complete -c solv -l arch
complete -c solv -l type

