# sqlsharp
# Autogenerated from man page /usr/local/share/man/man1/sqlsharp.1
complete -c sqlsharp -s f -d 'Output file to load SQL commands from'
complete -c sqlsharp -s o -d 'Output file to send results'
complete -c sqlsharp -s s -d 'Silent mode'

