# ssdeep
# Autogenerated from man page /opt/homebrew/share/man/man1/ssdeep.1
complete -c ssdeep -s m -d 'Loads the specified file of known hashes to be used for matching'
complete -c ssdeep -s k -d 'Load the specified file of known hashes to be used for matching'
complete -c ssdeep -s v -d 'Verbose mode'
complete -c ssdeep -s d -d 'Computes a signature for each entry in the FILES and compares it to the set o…'
complete -c ssdeep -s p -d 'Works like the -d flag, but displays all matches for each file'
complete -c ssdeep -s r -d 'Enables recursive mode.  All subdirectories are traversed'
complete -c ssdeep -s g -d 'Similar files are grouped together into clusters'
complete -c ssdeep -s s -d 'Silent mode.  All error messages are suppressed'
complete -c ssdeep -s b -d 'Enables bare mode'
complete -c ssdeep -s l -d 'Enables relative file paths'
complete -c ssdeep -s c -d 'Enables comma separated output mode'
complete -c ssdeep -s x -d 'Signature file matching'
complete -c ssdeep -s a -d 'Displays all matches in any of the matching mode, regardless of score'
complete -c ssdeep -s t -d 'In any of the matching modes, only display matches when match score is greate…'
complete -c ssdeep -s h -d 'Show a help screen and exit'
complete -c ssdeep -s V -d 'Show the version number and exit'

