# tcpserver
# Autogenerated from man page /opt/homebrew/share/man/man1/tcpserver.1
complete -c tcpserver -o climit -d 'Do not handle more than  limit simultaneous connections'
complete -c tcpserver -o 'xrules.cdb' -d 'Follow the rules compiled into  rules. cdb by  tcprules '
complete -c tcpserver -o Bbanner -d 'Write  banner to the network immediately after each connection is made'
complete -c tcpserver -o ggid -d 'Switch group ID to  gid after preparing to receive connections'
complete -c tcpserver -o uuid -d 'Switch user ID to   uid after preparing to receive connections'
complete -c tcpserver -s 1 -d 'After preparing to receive connections, print the local port number to standa…'
complete -c tcpserver -s 4 -d 'Fall back to IPv4 sockets'
complete -c tcpserver -s 6 -d 'Force IPv6 mode in UCSPI environment variables, even for IPv4 connections'
complete -c tcpserver -o Iinterface -d 'Bind to the network interface  interface ("eth0" on Linux, for example)'
complete -c tcpserver -o bbacklog -d 'Allow up to  backlog simultaneous SYN_RECEIVEDs.  Default: 20'
complete -c tcpserver -s o -d 'Leave IP options alone'
complete -c tcpserver -s O -d '(Default. ) Kill IP options'
complete -c tcpserver -s d -d '(Default'
complete -c tcpserver -s D -d 'Never delay sending data; enable TCP_NODELAY'
complete -c tcpserver -s q -d 'Quiet.  Do not print any messages'
complete -c tcpserver -s Q -d '(Default. ) Print error messages'

