# texindex
# Autogenerated from man page /opt/homebrew/share/man/man1/texindex.1
complete -c texindex -s h -l help -d 'display this help and exit'
complete -c texindex -l version -d 'display version information and exit'

