# textunderstandingd
# Autogenerated from man page /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/textunderstandingd.1
complete -c textunderstandingd -s a -d 'Description of -a flag'
complete -c textunderstandingd -s b -d 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

