# virt-qemu-run
# Autogenerated from man page /opt/homebrew/share/man/man1/virt-qemu-run.1
complete -c virt-qemu-run -s r -l root
complete -c virt-qemu-run -s s
complete -c virt-qemu-run -l secret
complete -c virt-qemu-run -s v -l verbose
complete -c virt-qemu-run -s h -l help

