# virt-ssh-helper
# Autogenerated from man page /opt/homebrew/share/man/man8/virt-ssh-helper.8
complete -c virt-ssh-helper -s r -l readonly
complete -c virt-ssh-helper -s h -l help
complete -c virt-ssh-helper -s V -l version

