# wormhole
# Autogenerated from man page /opt/homebrew/share/man/man1/wormhole.1
complete -c wormhole -l relay-url -d 'rendezvous relay to use'
complete -c wormhole -l transit-helper -d 'transit relay to use'
complete -c wormhole -l dump-timing -d '(debug) write timing data to file'
complete -c wormhole -l version -d 'Show the version and exit'
complete -c wormhole -l help -d 'Show this message and exit. SS "Commands:"'

