# xcmsdb
# Autogenerated from man page /opt/X11/share/man/man1/xcmsdb.1
complete -c xcmsdb -o query -d 'This option attempts to read the XDCCC properties off the screen\'s root window'
complete -c xcmsdb -o remove -d 'This option attempts to remove the XDCCC properties on the screen\'s root wind…'
complete -c xcmsdb -o 'format\\032' -d 'Specifies the property format (32, 16, or 8 bits per entry) for the XDCCC_LIN…'
complete -c xcmsdb -o help -d 'This option prints a summary of the available options and exits'

