# xcompmgr
# Autogenerated from man page /opt/X11/share/man/man1/xcompmgr.1
complete -c xcompmgr -s d -d 'Specifies the display to manage'
complete -c xcompmgr -s r -d 'Specifies the blur radius for client-side shadows'
complete -c xcompmgr -s o -d 'Specifies the opacity for client-side shadows'
complete -c xcompmgr -s l -d 'Specifies the left offset for client-side shadows'
complete -c xcompmgr -s t -d 'Specifies the top offset for client-side shadows'
complete -c xcompmgr -s I -d 'Specifies the opacity change between steps while fading in'
complete -c xcompmgr -s O -d 'Specifies the opacity change between steps while fading out'
complete -c xcompmgr -s D -d 'Specifies the time (in milliseconds) between steps in a fade'
complete -c xcompmgr -s a -d 'Automatic server-side compositing'
complete -c xcompmgr -s c -d 'Client-side compositing with soft shadows and translucency support'
complete -c xcompmgr -s f -d 'When -c is specified, enables a smooth fade effect for transient windows like…'
complete -c xcompmgr -s n -d 'Simple client-side compositing.  This is the default mode'
complete -c xcompmgr -s s -d 'Server-side compositing with hard-edged shadows'
complete -c xcompmgr -s C -d 'When -c is specified, attempts to avoid painting shadows on panels and docks'
complete -c xcompmgr -s F -d 'When -f is specified, also enables the fade effect when windows change their …'
complete -c xcompmgr -s S -d 'Enables synchronous operation.   Useful for debugging'

