# xlsatoms
# Autogenerated from man page /opt/X11/share/man/man1/xlsatoms.1
complete -c xlsatoms -o display -d 'This option specifies the X server to which to connect'
complete -c xlsatoms -o format -d 'This option specifies a printf-style string used to list each atom <value,nam…'
complete -c xlsatoms -o range -d 'This option specifies the range of atom values to check'
complete -c xlsatoms -o name -d 'This option specifies the name of an atom to list'

