# Xquartz
# Autogenerated from man page /opt/X11/share/man/man1/Xquartz.1
complete -c Xquartz -o fakebuttons -d 'Same as enable_fake_buttons above with value true'
complete -c Xquartz -o nofakebuttons -d 'Same as enable_fake_buttons above with value false'
complete -c Xquartz -o fakemouse2 -d 'Same as fake_button2 above'
complete -c Xquartz -o fakemouse3 -d 'Same as fake_button3 above'
complete -c Xquartz -o depth -d 'Same as depth above'

