# xsetpointer
# Autogenerated from man page /opt/X11/share/man/man1/xsetpointer.1
complete -c xsetpointer -s l -d 'Lists the available devices'
complete -c xsetpointer -s c -d 'Toggles the sending of core input events, for servers which implement a virtu…'

