# xsm
# Autogenerated from man page /opt/X11/share/man/man1/xsm.1
complete -c xsm -o display -d 'Causes xsm to connect to the specified X display'
complete -c xsm -o session -d 'Causes xsm to load the specified session, bypassing the session menu'
complete -c xsm -o verbose -d 'Turns on debugging information.  SETUP '

