# yaa
# Autogenerated from man page /usr/share/man/man1/yaa.1
complete -c yaa -o ddir -d 'Target directory for archive/extract.  Default is the current directory'
complete -c yaa -o iinput_file -d 'Input file.  Default is stdin'
complete -c yaa -o ooutput_file -d 'Output file.  Default is stdout'
complete -c yaa -o subdirsubdir -d 'Path to archive under dir'
complete -c yaa -o Ddir_and_subdir -d 'Set both dir to `dirname dir_and_subdir` and subdir to `basename dir_and_subd…'
complete -c yaa -o aalgorithm -d 'Compression algorithm used when creating archives'
complete -c yaa -o bblock_size -d 'Block size used when compressing archives, a number with optional b, k, m, g …'
complete -c yaa -o tworker_threads -d 'Number of worker threads compressing/decompressing data'
complete -c yaa -o wtwriter_threads -d 'Number of writer threads extracting archive content'
complete -c yaa -o imanifestinput_manifest_file -d 'Manifest matching the input archive'
complete -c yaa -o omanifestoutput_manifest_file -d 'Receives a manifest of the output archive'
complete -c yaa -o no-enable-dedup -d 'If set, and SLC fields are present in the archive, files with same data will …'
complete -c yaa -o no-enable-holes -d 'If set, and the filesystem supports it, detect and create holes in files to s…'
complete -c yaa -o no-ignore-eperm -d 'If set, ignore EPERM (operation not permitted) errors when setting files attr…'
complete -c yaa -o exclude-regex -d 'Exclude entry paths matching regular expression expr, see re_format(7)'
complete -c yaa -o exclude-name -d 'Exclude entry paths where a single component of the path matches exactly name'
complete -c yaa -o include-type -d 'Include only entries matching the given types'
complete -c yaa -o password-value -d Password

