# yabai
# Autogenerated from man page /opt/homebrew/share/man/man1/yabai.1
complete -c yabai -s v -l version
complete -c yabai -s V -l verbose
complete -c yabai -s m -l message
complete -c yabai -s c -l config
complete -c yabai -l uninstall-sa
complete -c yabai -l load-sa
complete -c yabai -l install-service
complete -c yabai -l uninstall-service
complete -c yabai -l start-service
complete -c yabai -l restart-service
complete -c yabai -l stop-service
complete -c yabai -l focus
complete -c yabai -l create
complete -c yabai -l destroy
complete -c yabai -l move
complete -c yabai -l swap
complete -c yabai -l display
complete -c yabai -l balance
complete -c yabai -l mirror
complete -c yabai -l rotate
complete -c yabai -l padding
complete -c yabai -l gap
complete -c yabai -l toggle
complete -c yabai -l layout
complete -c yabai -l label
complete -c yabai -l warp
complete -c yabai -l stack
complete -c yabai -l insert
complete -c yabai -l grid
complete -c yabai -l resize
complete -c yabai -l ratio
complete -c yabai -l layer
complete -c yabai -l opacity
complete -c yabai -l space
complete -c yabai -l minimize
complete -c yabai -l deminimize
complete -c yabai -l close
complete -c yabai -l displays
complete -c yabai -l spaces
complete -c yabai -l windows
complete -c yabai -l window
complete -c yabai -l add
complete -c yabai -l remove
complete -c yabai -l list

