# zic
# Autogenerated from man page /usr/share/man/man8/zic.8
complete -c zic -s g -d 'After creating each output file, change its group ownership to the specified …'
complete -c zic -s m -d 'After creating each output file, change its access mode to mode'
complete -c zic -s u -d 'After creating each output file, change its owner to user (which can be eithe…'
complete -c zic -s s -d 'Limit time values stored in output files to values that are the same whether …'
complete -c zic -s y -d 'Use the given command rather than yearistype when checking year types (see be…'

