#!/usr/bin/env bash
#
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

source "${HOME}/.local/bin/helper"

# Unload the macOS WindowManager process

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=display_added action="sleep 1 && source ${HOME}/.local/bin/helper && create_spaces 7"
yabai -m signal --add event=display_removed action="sleep 1 && source ${HOME}/.local/bin/helper && create_spaces 7"



# BAR HEIGHT
BAR_HEIGHT=20

GENERAL=(
	external_bar all:"${BAR_HEIGHT}":0
	split_type auto
	split_ratio 0.5
	auto_balance off
	insert_feedback_color 0xff7793d1
)

WINDOWS=(
	window_placement second_child
	window_topmost on
	window_shadow float
	window_opacity on
	active_window_opacity 1.0
	normal_window_opacity 0.9
	window_animation_duration 0.0
	window_origin_display focused
	window_opacity_duration 0.15
)

BORDERS=(
	window_border on
	window_border_blur off
	window_border_hidpi on
	window_border_width 2
	window_border_radius 12
	active_window_border_color 0xffffffff
	normal_window_border_color 0xff5e6798
)
# window_border_radius 11 \

LAYOUT=(
	layout float
	top_padding 10
	bottom_padding 60
	left_padding 10
	right_padding 10
	window_gap 10
)

MOUSE=(
	mouse_modifier fn
	mouse_action1 move
	mouse_action2 resize
	mouse_drop_action swap
	focus_follows_mouse autoraise
	mouse_follows_focus off
)

yabai -m config "${GENERAL[@]}"
yabai -m config "${WINDOWS[@]}"
yabai -m config "${BORDERS[@]}"
yabai -m config "${LAYOUT[@]}"
yabai -m config "${MOUSE[@]}"
