#!/usr/bin/env zsh
#

# Load required modules for git info.
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats " %F{blue}(%b%u)%f"

precmd() {
  vcs_info
  PS1="%F{green}anti%f %F{yellow}%~%f${vcs_info_msg_0_} %F{green}$ %f"
}

# This ensures vcs_info sets the variable properly.
precmd



if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM='xterm-256color';
fi;
