#!/bin/bash


if [ "$#" -ne 3 ]; then
  echo "Usage: <username/repo> <branch> <file-or-directory-path>"
  exit 1
fi


REPO_SLUG="$1"
BRANCH="$2"
FILE_PATH="$3"
REPO_URL="https://github.com/$REPO_SLUG.git"
REPO_NAME=$(basename "$REPO_SLUG")

# Clone the repository without checking out files (--no-checkout)
git clone -n --depth=1 --filter=blob:none --branch "$BRANCH" "$REPO_URL" "$REPO_NAME"
cd "$REPO_NAME"


git sparse-checkout init --cone

git sparse-checkout set "$FILE_PATH"


git checkout

echo "The specified file or directory has been checked out."

