# arm64-apple-darwin20.0.0-nmedit
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-nmedit.1
complete -c 'arm64-apple-darwin20.0.0-nmedit' -s s -d 'Leave the symbol table entries for the global symbols listed in  filename glo…'
complete -c 'arm64-apple-darwin20.0.0-nmedit' -s R -d 'Change the symbol table entries for the global symbols listed in  filename in…'
complete -c 'arm64-apple-darwin20.0.0-nmedit' -s p -d 'Change symbols to private externs instead of static'
complete -c 'arm64-apple-darwin20.0.0-nmedit' -s A -d 'Leave all global absolute symbols except those with a value of zero, and save…'
complete -c 'arm64-apple-darwin20.0.0-nmedit' -o arch -d 'Specifies the architecture,  arch_type, of the file for R nmedit (1) to proce…'
complete -c 'arm64-apple-darwin20.0.0-nmedit' -s g -d 'option to cc (1)) for the global symbols it changes to static symbols so that…'
complete -c 'arm64-apple-darwin20.0.0-nmedit' -s o -d 'Write the result into the file output.  SEE ALSO strip(1), ld(1), arch(3)'

