# arm64-apple-darwin20.0.0-pagestuff
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-pagestuff.1
complete -c 'arm64-apple-darwin20.0.0-pagestuff' -o arch -d 'Specifies the architecture,  arch_type, of the file for R pagestuff (1) to op…'
complete -c 'arm64-apple-darwin20.0.0-pagestuff' -s a -d 'Displays all pages.   All other arguments are ignored'
complete -c 'arm64-apple-darwin20.0.0-pagestuff' -s p -d 'Print a list of the sections of the specified Mach-O file, with offsets and l…'

