# arm64-apple-darwin20.0.0-strings
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-strings.1
complete -c 'arm64-apple-darwin20.0.0-strings' -s a -d 'This option causes  strings to look for strings in all sections of the object…'
complete -c 'arm64-apple-darwin20.0.0-strings' -s o -d 'Preceded each string by its offset in the file (in decimal)'
complete -c 'arm64-apple-darwin20.0.0-strings' -s t -d 'Write each string preceded by its byte offset from the start of the file'
complete -c 'arm64-apple-darwin20.0.0-strings' -s n -d 'Specify the minimum string length, where the number argument is a positive de…'
complete -c 'arm64-apple-darwin20.0.0-strings' -o arch -d 'Specifies the architecture, arch_type, of the file for strings (1) to operate…'

