# arm64-apple-darwin20.0.0-check_dylib
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-check_dylib.1
complete -c 'arm64-apple-darwin20.0.0-check_dylib' -o install_name -d 'argument and if it does not match it exit with a value of 2'
complete -c 'arm64-apple-darwin20.0.0-check_dylib' -o seg_addr_table -d 'for an entry with the path_name argument of the'
complete -c 'arm64-apple-darwin20.0.0-check_dylib' -o seg_addr_table_filename -d 'and if one is not found in the table exit with a value of 3'

