# buddy-ng
# Autogenerated from man page /opt/homebrew/share/man/man1/buddy-ng.1
complete -c buddy-ng -s h -d 'Shows the help screen'
complete -c buddy-ng -s p -d 'Don\'t drop privileges AUTHOR This manual page was written by Thomas d\'Otreppe'

