# cifer
# Autogenerated from man page /opt/homebrew/share/man/man1/cifer.1
complete -c cifer -s n -d 'Disable auto-init'
complete -c cifer -s f -d 'Execute the commands in the (script) file specified, then exit'
complete -c cifer -s i -d 'Execute the script file and then go to interactive mode'
complete -c cifer -s q -d 'Do not fully parse file before execution'
complete -c cifer -s s -d 'Exit on soft-fails, not just hard-fails (for script execution)'

