# cryptexctl-uninstall
# Autogenerated from man page /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man1/cryptexctl-uninstall.1
complete -c cryptexctl-uninstall -s i -d 'Force physical uninstalltion to happen immediately if possible'

