# dotnet-new
# Autogenerated from man page /opt/homebrew/share/man/man1/dotnet-new.1
complete -c dotnet-new -l dry-run -d 'Displays a summary of what would happen if the given command were run if it w…'
complete -c dotnet-new -l force -d 'Forces content to be generated even if it would change existing files'
complete -c dotnet-new -s '?' -s h -l help -d 'Prints out help for the command'
complete -c dotnet-new -o lang -l language -d 'The language of the template to create'
complete -c dotnet-new -s n -l name -d 'The name for the created output'
complete -c dotnet-new -o no-update-check -d 'Disables checking for template package updates when instantiating a template'
complete -c dotnet-new -s o -l output -d 'Location to place the generated output.  The default is the current directory'

