# dotnet-list-reference
# Autogenerated from man page /opt/homebrew/share/man/man1/dotnet-list-reference.1
complete -c dotnet-list-reference -s '?' -s h -l help -d 'Prints out a description of how to use the command'

