# fstobdf
# Autogenerated from man page /opt/X11/share/man/man1/fstobdf.1
complete -c fstobdf -o server -d 'This option specifies the server from which the font should be read'
complete -c fstobdf -o fn -d 'This option specifies the font for which a BDF file should be generated'
complete -c fstobdf -o version -d 'This option prints the program version and then exits without generating a BD…'

