# git-config
# Autogenerated from man page /opt/homebrew/share/man/man1/git-config.1
complete -c git-config -l gui -d 'argument), or auto to select diff. guitool or diff'
complete -c git-config -l bundle-uri -d 'option behaves in git-clone(1).  git clone --bundle-uri will set the fetch'
complete -c git-config -l stdout -d 'is in use to escape "^>+From " lines.  format. noprefix'
complete -c git-config -o p0 -d 'option.  filter. <driver>. clean'
complete -c git-config -l no-rebase-merges

