# git-crypt
# Autogenerated from man page /opt/homebrew/share/man/man1/git-crypt.1
complete -c git-crypt -s k -l key-name
complete -c git-crypt -s e
complete -c git-crypt -s u
complete -c git-crypt -s f -l fix
complete -c git-crypt -s n -l no-commit
complete -c git-crypt -l trusted

