# git-format-patch
# Autogenerated from man page /opt/homebrew/share/man/man1/git-format-patch.1
complete -c git-format-patch -l default-prefix -d 'Use the default source and destination prefixes ("a/" and "b/")'

