# git-diff-files
# Autogenerated from man page /opt/homebrew/share/man/man1/git-diff-files.1
complete -c git-diff-files -l default-prefix -d 'Use the default source and destination prefixes ("a/" and "b/")'

