# gsleep
# Autogenerated from man page /opt/homebrew/share/man/man1/gsleep.1
complete -c gsleep -l help -d 'display this help and exit'
complete -c gsleep -l version -d 'output version information and exit AUTHOR Written by Jim Meyering and Paul E…'

