# gst-typefind-1.0
# Autogenerated from man page /opt/homebrew/share/man/man1/gst-typefind-1.0.1
complete -c 'gst-typefind-1.0' -l gst-plugin-path -d 'Add directories separated with \':\' to the plugin search path'

