# gst-inspect-1.0
# Autogenerated from man page /opt/homebrew/share/man/man1/gst-inspect-1.0.1
complete -c 'gst-inspect-1.0' -l no-colors -d 'Disable colors in output'
complete -c 'gst-inspect-1.0' -s C -l color -d 'Color output, even when not connected to a tty'

