# gupdatedb
# Autogenerated from man page /opt/homebrew/share/man/man1/gupdatedb.1
complete -c gupdatedb -l findoptions -o 'option2...\'' -d 'Global options to pass on to find'
complete -c gupdatedb -l localpaths -d 'Non-network directories to put in the database.  Default is /'
complete -c gupdatedb -l netpaths -d 'Network (NFS, AFS, RFS, etc. ) directories to put in the database'
complete -c gupdatedb -l prunepaths -d 'Directories to not put in the database, which would otherwise be'
complete -c gupdatedb -l prunefs -d 'File systems to not put in the database, which would otherwise be'
complete -c gupdatedb -l output -d 'The database file to build.  Default is system-dependent'
complete -c gupdatedb -l localuser -d 'The user to search non-network directories as, using su(1)'
complete -c gupdatedb -l netuser -d 'The user to search network directories as, using su(1).  Default is daemon'
complete -c gupdatedb -l dbformat -d 'Create the database in format F.   The default format is called LOCATE02'
complete -c gupdatedb -l version -d 'Print the version number of  updatedb and exit'
complete -c gupdatedb -l help -d 'Print a summary of the options to updatedb and exit'

