# iconv
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/iconv.1
complete -c iconv -l from-code -d 'Specifies the encoding of the input'
complete -c iconv -l to-code -d 'Specifies the encoding of the output'
complete -c iconv -l unicode-subst -d 'When this option is given, Unicode characters that cannot be represented in t…'
complete -c iconv -l byte-subst -d 'When this option is given, bytes in the input that are not valid in the sourc…'
complete -c iconv -l widechar-subst -d 'When this option is given, wide characters in the input that are not valid in…'
complete -c iconv -l silent -d 'When this option is given, error messages about invalid or unconvertible char…'

