# json-glib-format
# Autogenerated from man page /opt/homebrew/share/man/man1/json-glib-format.1
complete -c json-glib-format -s h -l help
complete -c json-glib-format -l output
complete -c json-glib-format -s p -l prettify
complete -c json-glib-format -l indent-spaces

