# koi8rxterm
# Autogenerated from man page /opt/X11/share/man/man1/koi8rxterm.1
complete -c koi8rxterm -o class -d and
complete -c koi8rxterm -o k8 -d 'options should not be specified because they are used by the wrapper'

