# lzma
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/lzma.1
complete -c lzma -l memlimit-mt-decompress -d 'Set a memory usage limit for multi-threaded decompression'
complete -c lzma -l arm64

