# pdfimages
# Autogenerated from man page /opt/homebrew/share/man/man1/pdfimages.1
complete -c pdfimages -s f -d 'Specifies the first page to scan'
complete -c pdfimages -s l -d 'Specifies the last page to scan'
complete -c pdfimages -s j -d 'Normally, all images are written as PBM (for monochrome images), PGM (for gra…'
complete -c pdfimages -o raw -d 'Write all images in PDF-native formats'
complete -c pdfimages -o list -d 'Write a one-line summary to stdout for each image'
complete -c pdfimages -o opw -d 'Specify the owner password for the PDF file'
complete -c pdfimages -o upw -d 'Specify the user password for the PDF file'
complete -c pdfimages -o verbose -d 'Print a status message (to stdout) before processing each page'
complete -c pdfimages -s q -d 'Don\'t print any messages or errors. RB "[config file: " errQuiet ]'
complete -c pdfimages -s v -d 'Print copyright and version information'
complete -c pdfimages -s h -d 'Print usage information.  ( -help and'
complete -c pdfimages -l help -d 'are equivalent. ) EXIT CODES The Xpdf tools use the following exit codes:'

