# pgtopo_export
# Autogenerated from man page /Applications/Postgres.app/Contents/Versions/latest/share/man/man1/pgtopo_export.1
complete -c pgtopo_export -s f -d 'Write the output to a particular filename instead of stadard output'

