# psusan
# Autogenerated from man page /opt/homebrew/share/man/man1/psusan.1
complete -c psusan -l listen -d 'Run psusan in listening mode'
complete -c psusan -l listen-once -d 'In listening mode, this option causes psusan to listen for only one connectio…'
complete -c psusan -l sessiondir -d 'This option sets the directory that shell sessions and subprocesses will star…'
complete -c psusan -s v -l verbose -d 'This option causes psusan to print verbose log messages on its standard error'
complete -c psusan -o sshlog
complete -c psusan -o sshrawlog -d 'These options cause psusan to log protocol details to a file, similarly to th…'

