# repo2solv
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/repo2solv.1
complete -c repo2solv -s o
complete -c repo2solv -s R
complete -c repo2solv -s F
complete -c repo2solv -s C
complete -c repo2solv -s A
complete -c repo2solv -s X

