# unxz
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/unxz.1
complete -c unxz -l memlimit-mt-decompress -d 'Set a memory usage limit for multi-threaded decompression'
complete -c unxz -l arm64

