# virt-host-validate
# Autogenerated from man page /opt/homebrew/share/man/man1/virt-host-validate.1
complete -c virt-host-validate -s v -l version
complete -c virt-host-validate -s h -l help
complete -c virt-host-validate -s q -l quiet

