# xclip-copyfile
# Autogenerated from man page /opt/homebrew/share/man/man1/xclip-copyfile.1
complete -c xclip-copyfile -s p -d 'preserve path formation xclip-pastefile pastes the files out of the clipboard…'

