# arm64-apple-darwin20.0.0-seg_addr_table
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-seg_addr_table.1
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -s o -d 'Write the new segment address table to  output_file'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o relayout -d 'This causes the entire table to be re-laied out and all dynamic libraries to …'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o update -d 'Only entries with zero address values are assigned addresses'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o update_overlaps -d 'Detects overlaps in the table and reassigns the lower of the two addresses'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o relayout_nonsplit -d 'Similar to relayout except it only causes all the non split libraries to re-l…'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o checkonly -d 'This option only checks the entries in the table for overlaps'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o seg_addr_table -d 'This is the input segment address table'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o release -d 'For each ``flat\'\' entry in the table try finding and using the dynamic librar…'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o seg1addr -d 'Specifies the starting address to layout ``flat\'\' libraries'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o allocate_flat -d 'Specifies which  direction to allocate flat addresses into'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o segs_read_only_addr -d 'Specifies the starting address to layout the read-only segments of ``split\'\' …'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o segs_read_write_addr -d 'Specifies the starting address to layout the read-write segments of ``split\'\'…'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o disablewarnings -d 'This option disables a small number of warnings which is useful for B&I when …'
complete -c 'arm64-apple-darwin20.0.0-seg_addr_table' -o arch -d 'Specifies the architecture, arch_type, in the files to use for the sizes'

