# arm64-apple-darwin20.0.0-dyldinfo
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-dyldinfo.1
complete -c 'arm64-apple-darwin20.0.0-dyldinfo' -o arch -d 'Only display the specified architecture'
complete -c 'arm64-apple-darwin20.0.0-dyldinfo' -o dylibs -d 'Display the table of dylibs on which this image depends'
complete -c 'arm64-apple-darwin20.0.0-dyldinfo' -o rebase -d 'Display the table of rebasing information'
complete -c 'arm64-apple-darwin20.0.0-dyldinfo' -o bind -d 'Display the table of binding information'
complete -c 'arm64-apple-darwin20.0.0-dyldinfo' -o weak_bind -d 'Display the table of weak binding information'
complete -c 'arm64-apple-darwin20.0.0-dyldinfo' -o lazy_bind -d 'Display the table of lazy binding information'
complete -c 'arm64-apple-darwin20.0.0-dyldinfo' -o export -d 'Display the table symbols which this image exports'
complete -c 'arm64-apple-darwin20.0.0-dyldinfo' -o opcodes -d 'Display the low level opcodes used to encode all rebase and binding informati…'
complete -c 'arm64-apple-darwin20.0.0-dyldinfo' -o function_starts -d 'Decodes the list of function start addresses.  El SEE ALSO otool 1 nm 1'

