# arm64-apple-darwin20.0.0-bitcode_strip
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-bitcode_strip.1
complete -c 'arm64-apple-darwin20.0.0-bitcode_strip' -s o -d 'specifies the output file as  output'
complete -c 'arm64-apple-darwin20.0.0-bitcode_strip' -s r -d 'specifies the bitcode segment is to be removed'
complete -c 'arm64-apple-darwin20.0.0-bitcode_strip' -s m -d 'specifies the bitcode segment is to be removed and a marker is left'
complete -c 'arm64-apple-darwin20.0.0-bitcode_strip' -s l -d 'specifies that only the bitcode segment and the (__TEXT,__info_plist) section…'

