# arm64-apple-darwin20.0.0-indr
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/arm64-apple-darwin20.0.0-indr.1
complete -c 'arm64-apple-darwin20.0.0-indr' -s n -d 'Suppress creating the indirect objects when the output file is an archive'
complete -c 'arm64-apple-darwin20.0.0-indr' -o arch -d 'Specifies the architecture,  arch_type, of the file for R indr (1) to process…'

