# calcurse
# Autogenerated from man page /opt/homebrew/share/man/man1/calcurse.1
complete -c calcurse -s a -l appointment -d 'Print the appointments and events for the current day'
complete -c calcurse -s c -l calendar -d '(also interactively) Specify the calendar file to use'
complete -c calcurse -s C -l confdir -d '(also interactively) Specify the configuration directory to use'
complete -c calcurse -s D -l datadir -d '(also interactively) Specify the (data) directory to use'
complete -c calcurse -s d -l day -d 'Print appointments and events for the given date or given range of days, depe…'
complete -c calcurse -l daemon -d 'Start calcurse in background mode; restart, if the daemon was already running'
complete -c calcurse -l days -d 'Specify the range of days when used with -Q'
complete -c calcurse -l dump-imported -d 'When importing items, print each newly created object to stdout'
complete -c calcurse -l export-uid -d 'When exporting items, add the hash of each item to the exported object as a U…'
complete -c calcurse -l from -d 'Specify the start date of the day range when used with -Q'
complete -c calcurse -s F -l filter -d 'Deprecated, see -P'
complete -c calcurse -s g -l gc -d 'Run the garbage collector for note files'
complete -c calcurse -s G -l grep -d 'Print appointments, events and TODO items in calcurse data file format'
complete -c calcurse -s h -l help -d 'Print a short help text describing the supported command-line options'
complete -c calcurse -s i -l import -d 'Import the icalendar data contained in file'
complete -c calcurse -l input-datefmt -d 'For command line and script use only: override the configuration file setting…'
complete -c calcurse -s l -l limit -d 'Limit the number of results printed to num'
complete -c calcurse -s n -l next -d 'Print the first appointment within the next 24 hours'
complete -c calcurse -l output-datefmt -d 'For command line and script use only: override the configuration file setting…'
complete -c calcurse -s P -l purge -d 'Load items from the data files and save them back; the items are described by…'
complete -c calcurse -s q -l quiet -d '(also interactively) Be quiet.  Do not show system dialogs'
complete -c calcurse -s Q -l query -d 'Print all appointments and events in a given range of days followed by all TO…'
complete -c calcurse -s r -l range -d 'Print appointments and events for num number of days starting with the curren…'
complete -c calcurse -l read-only -d '(also interactively) Do not save configuration nor appointments and todos'
complete -c calcurse -s s -l startday -d 'Print events and appointments from the optional date; default is the current …'
complete -c calcurse -s S -l search -d 'When used with any of -a, -d, -r, -s, or -t print only the items having a des…'
complete -c calcurse -l status -d 'Display the status of running instances of calcurse, interactive or backgroun…'
complete -c calcurse -s t -l todo -d 'Print the todo list'
complete -c calcurse -l to -d 'Specify the end date of the day range when used with -Q'
complete -c calcurse -s v -l version -d 'Display calcurse version'
complete -c calcurse -s x -l export -d 'Export user data in the specified format'
complete -c calcurse -l filter-type
complete -c calcurse -o to -d or
complete -c calcurse -l filter-invert
complete -c calcurse -l to/--days
complete -c calcurse -l filter-pattern -d regex
complete -c calcurse -l filter-priority -d and
complete -c calcurse -l filter-completed -d or
complete -c calcurse -l filter-uncompleted
complete -c calcurse -l filter-hash
complete -c calcurse -l filter-start-from
complete -c calcurse -l filter-start-to
complete -c calcurse -l filter-start-after
complete -c calcurse -l filter-start-before
complete -c calcurse -l filter-start-range
complete -c calcurse -l filter-end-from
complete -c calcurse -l filter-end-to
complete -c calcurse -l filter-end-after
complete -c calcurse -l filter-end-before
complete -c calcurse -l filter-end-range
complete -c calcurse -l format-apt -l format-recur-apt -l format-event -l format-recur-event -l format-todo
complete -c calcurse -s '>'

