# cjpeg
# Autogenerated from man page /opt/homebrew/share/man/man1/cjpeg.1
complete -c cjpeg -o precision -d 'Create JPEG file with N-bit data precision.   N is 8, 12, or 16; default is 8'
complete -c cjpeg -o lossless -d 'Create a lossless JPEG file using the specified predictor selection value (1 …'

