# dotnet-new-search
# Autogenerated from man page /opt/homebrew/share/man/man1/dotnet-new-search.1
complete -c dotnet-new-search -l author -d 'Filters templates based on template author.  Partial match is supported'
complete -c dotnet-new-search -l columns -d 'Comma-separated list of columns to display in the output'
complete -c dotnet-new-search -l columns-all -d 'Displays all columns in the output'
complete -c dotnet-new-search -o lang -l language -d 'Filters templates based on language supported by the template'
complete -c dotnet-new-search -l package -d 'Filters templates based on NuGet package ID.  Partial match is supported'
complete -c dotnet-new-search -l tag -d 'Filters templates based on template tags'
complete -c dotnet-new-search -l type -d 'Filters templates based on template type'

