# fslsfonts
# Autogenerated from man page /opt/X11/share/man/man1/fslsfonts.1
complete -c fslsfonts -o server -d 'This option specifies the X font server to contact'
complete -c fslsfonts -s l -d 'Lists some attributes of the font on one line in addition to its name'
complete -c fslsfonts -o ll -d 'Lists font properties in addition to -l output'
complete -c fslsfonts -o lll -d 'Supported for compatibility with xlsfonts, but output is the same as for -ll'
complete -c fslsfonts -s m -d 'This option indicates that long listings should also print the minimum and ma…'
complete -c fslsfonts -s C -d 'This option indicates that listings should use multiple columns'
complete -c fslsfonts -s 1 -d 'This option indicates that listings should use a single column'
complete -c fslsfonts -s w -d 'This option specifies the width in characters that should be used in figuring…'
complete -c fslsfonts -s n -d 'This option specifies the number of columns to use in displaying the output'
complete -c fslsfonts -s u -d 'This option indicates that the output should be left unsorted'

