# git-lfs-push
# Autogenerated from man page /opt/homebrew/share/man/man1/git-lfs-push.1
complete -c git-lfs-push -l dry-run
complete -c git-lfs-push -l all
complete -c git-lfs-push -l object-id
complete -c git-lfs-push -l stdin

