# git-sparse-checkout
# Autogenerated from man page /opt/homebrew/share/man/man1/git-sparse-checkout.1
complete -c git-sparse-checkout -l rules-file -d 'flag the input files are matched against the sparse checkout rules found in <…'
complete -c git-sparse-checkout -s z -d 'flag, the format of the paths input on stdin as well as the output paths are …'

