# git-diff-index
# Autogenerated from man page /opt/homebrew/share/man/man1/git-diff-index.1
complete -c git-diff-index -l default-prefix -d 'Use the default source and destination prefixes ("a/" and "b/")'

