# git-lfs-prune
# Autogenerated from man page /opt/homebrew/share/man/man1/git-lfs-prune.1
complete -c git-lfs-prune -l dry-run -s d
complete -c git-lfs-prune -l force -s f
complete -c git-lfs-prune -l recent
complete -c git-lfs-prune -l verify-remote -s c
complete -c git-lfs-prune -l no-verify-remote
complete -c git-lfs-prune -l verbose -s v

