# git-lfs-fetch
# Autogenerated from man page /opt/homebrew/share/man/man1/git-lfs-fetch.1
complete -c git-lfs-fetch -s I -l include
complete -c git-lfs-fetch -s X -l exclude
complete -c git-lfs-fetch -l recent
complete -c git-lfs-fetch -l all
complete -c git-lfs-fetch -l include/--exclude -d 'exclude paths to ensure that all objects are downloaded'
complete -c git-lfs-fetch -l prune -s p

