# glink
# Autogenerated from man page /opt/homebrew/share/man/man1/glink.1
complete -c glink -l help -d 'display this help and exit'
complete -c glink -l version -d 'output version information and exit AUTHOR Written by Michael Stone'

