# gunlink
# Autogenerated from man page /opt/homebrew/share/man/man1/gunlink.1
complete -c gunlink -l help -d 'display this help and exit'
complete -c gunlink -l version -d 'output version information and exit AUTHOR Written by Michael Stone'

