# kadmind
# Autogenerated from man page /Users/anti/miniforge3/share/man/man8/kadmind.8
complete -c kadmind -s m -d 'causes the master database password to be fetched from the keyboard (before t…'
complete -c kadmind -o nofork -d 'causes the server to remain in the foreground and remain associated to the te…'
complete -c kadmind -o proponly -d 'causes the server to only listen and respond to Kerberos replica incremental …'
complete -c kadmind -o port -d 'specifies the port on which the administration server listens for connections'
complete -c kadmind -s P -d 'specifies the file to which the PID of kadmind process should be written afte…'
complete -c kadmind -s K -d 'specifies the path to the kprop command to use to send full dumps to replicas…'
complete -c kadmind -s F -d 'specifies the file path to be used for dumping the KDB in response to full re…'
complete -c kadmind -s x -d 'specifies database-specific arguments'

