# lzcat
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/lzcat.1
complete -c lzcat -l memlimit-mt-decompress -d 'Set a memory usage limit for multi-threaded decompression'
complete -c lzcat -l arm64

