# patch
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/patch.1
complete -c patch -s B -d 'Use the  simple method to determine backup file names (see the  "-V " method …'
complete -c patch -s d -d 'Change to the directory  dir immediately, before doing anything else'
complete -c patch -s D -d 'Use the  #ifdef " . \\|. \\|'
complete -c patch -s F -d 'Set the maximum fuzz factor'
complete -c patch -s i -d 'Read the patch from R patchfile '
complete -c patch -s o -d 'Send output to  outfile instead of patching files in place'
complete -c patch -o pnum -d 'Strip the smallest prefix containing  num leading slashes from each file name…'
complete -c patch -s r -d 'Put rejects into  rejectfile instead of the default  . rej file'
complete -c patch -s s -d 'Work silently, unless an error occurs'
complete -c patch -s V -d 'Use  method to determine backup file names'
complete -c patch -s x -d 'Set internal debugging flags of interest only to  patch patchers'
complete -c patch -s z -d 'Use the  simple method to determine backup file names (see the  "-V " method …'
complete -c patch -l option -d 'The names of the files to be patched are usually taken from the patch file, b…'
complete -c patch -l -e -l -n -l or
complete -c patch -s p -d or
complete -c patch -l Make -d 'That is, when patching a file, rename or copy the original instead of removin…'
complete -c patch -l Back -d 'and if backups are not otherwise requested'
complete -c patch -l Do -d 'and if backups are not otherwise requested'
complete -c patch -l Use -d 'simple method to determine backup file names (see the'
complete -c patch -l Write -d '/dev/tty '
complete -c patch -l Interpret
complete -c patch -l Change -d 'dir immediately, before doing anything else'
complete -c patch -l Print
complete -c patch -l Remove -d 'Normally this option is unnecessary, since patch can examine the time stamps …'
complete -c patch -l Assume -d 'ask any questions'
complete -c patch -l Set -d 'This option only applies to diffs that have context, and causes patch to igno…'
complete -c patch -l This -d 'patch \'s actions when a file is under RCS or SCCS control, and does not exist…'
complete -c patch -l Read -d 'patchfile .  If patchfile is'
complete -c patch -l Match -d 'have been munged in your files'
complete -c patch -l Merge -d 'merge(1)'
complete -c patch -l When -d 'has been applied already by trying to reverse-apply the first hunk.   The'
complete -c patch -l -R
complete -c patch -l Send -d 'outfile instead of patching files in place'
complete -c patch -l Strip -d 'num leading slashes from each file name found in the patch file'
complete -c patch -o p0 -d 'gives the entire file name unmodified,'
complete -c patch -o p1 -d 'gives u/howard/src/blurfl/blurfl. c without the leading slash,'
complete -c patch -o p4 -d 'gives blurfl/blurfl. c and not specifying'
complete -c patch -l Conform -d ' o Take the first existing file from the list (old, new, index) when intuitin…'
complete -c patch -l Put -d 'rejectfile instead of the default . rej file'
complete -c patch -l Behave -d 'potential problem, warn about it (the default), or fail'
complete -c patch -l Produce -d 'unified)'
complete -c patch -l Work
complete -c patch -l Suppress
complete -c patch -l -Y -d or
complete -c patch -l and
complete -c patch -l options -d 'If none of these options are given, then a simple backup suffix is used; it i…'
complete -c patch -l Output
complete -c patch -o Np1 -d 'is recommended'
complete -c patch -l -

