# pee
# Autogenerated from man page /opt/homebrew/share/man/man1/pee.1
complete -c pee -l ignore-sigpipe -l no-ignore-sigpipe -d 'Do (not) ignore SIGPIPE'
complete -c pee -l ignore-write-errors -l no-ignore-write-errors -d 'Do (not) ignore write errors'

