# pgsql2shp
# Autogenerated from man page /Applications/Postgres.app/Contents/Versions/latest/share/man/man1/pgsql2shp.1
complete -c pgsql2shp -s f -d 'Write the output to a particular filename'
complete -c pgsql2shp -s h -d 'The database host to connect to'
complete -c pgsql2shp -s p -d 'The port to connect to on the database host'
complete -c pgsql2shp -s P -d 'The password to use when connecting to the database'
complete -c pgsql2shp -s u -d 'The username to use when connecting to the database'
complete -c pgsql2shp -s g -d 'In the case of tables with multiple geometry columns, the geometry column  to…'
complete -c pgsql2shp -s b -d 'Use a binary cursor.  When used on pre-1. 0'
complete -c pgsql2shp -s r -d 'Raw mode.  Do not drop the gid field, or escape column names'
complete -c pgsql2shp -s d -d 'For backward compatibility: write a 3-dimensional shape file when dumping  fr…'
complete -c pgsql2shp -s k -d 'Keep identifiers case (don\'t uppercase field names)'
complete -c pgsql2shp -s m -d 'Specify a file containing a set of mappings of (long) column names to 10 char…'

