# pgtopo_import
# Autogenerated from man page /Applications/Postgres.app/Contents/Versions/latest/share/man/man1/pgtopo_import.1
complete -c pgtopo_import -l skip-layers -d 'Do not include layers in the output SQL script.  Just the topology schema'
complete -c pgtopo_import -l only-layers -d 'Do not include the topology schema in the output SQL script.  Just the layers'

