# pidof
# Autogenerated from man page /opt/homebrew/share/man/man1/pidof.1.gz
complete -c pidof -s l -d 'prints output in long format, rather than just PID numbers'
complete -c pidof -s k -d 'kill process(es) by name'
complete -c pidof -s h -s '?' -d 'print out help'
complete -c pidof -s v -d 'prints out version info on pidof'

