# python3
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/python3.1
complete -c python3 -l help-env -d 'Prints help about Python-specific environment variables and exits'
complete -c python3 -l help-xoptions -d 'Prints help about implementation-specific -X options and exits'
complete -c python3 -l help-all -d 'Prints complete usage information and exits'
complete -c python3 -s P -d 'Don\'t automatically prepend a potentially unsafe path to sys'

