# ssh-sk-helper
# Autogenerated from man page /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man8/ssh-sk-helper.8
complete -c ssh-sk-helper -s v -d 'Verbose mode'

