# tiffcrop
# Autogenerated from man page /opt/homebrew/share/man/man1/tiffcrop.1
complete -c tiffcrop -s 1 -d 'will be the one strip in that case'
complete -c tiffcrop -s D -d 'Debug and dump facility'

