# unlzma
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/unlzma.1
complete -c unlzma -l memlimit-mt-decompress -d 'Set a memory usage limit for multi-threaded decompression'
complete -c unlzma -l arm64

