# xdm
# Autogenerated from man page /opt/X11/share/man/man8/xdm.8
complete -c xdm -o config -d 'Names the configuration file, which specifies resources to control the behavi…'
complete -c xdm -o nodaemon -d 'Specifies ``false\'\' as the value for the DisplayManager. daemonMode resource'
complete -c xdm -o debug -d 'Specifies the numeric value for the DisplayManager. debugLevel resource'
complete -c xdm -o error -d 'Specifies the value for the DisplayManager. errorLogFile resource'
complete -c xdm -o resources -d 'Specifies the value for the DisplayManager*resources resource'
complete -c xdm -o server -d 'Specifies the value for the DisplayManager. servers resource'
complete -c xdm -o udpPort -d 'Specifies the value for the DisplayManager. requestPort resource'
complete -c xdm -o session -d 'Specifies the value for the DisplayManager*session resource'
complete -c xdm -o xrm -d 'Allows an arbitrary resource to be specified, as in most X Toolkit applicatio…'

