# xz
# Autogenerated from man page /opt/homebrew/anaconda3/share/man/man1/xz.1
complete -c xz -l memlimit-mt-decompress -d 'Set a memory usage limit for multi-threaded decompression'
complete -c xz -l arm64

